"""Command seeder for FieryMUD.

Seeds all MUD commands with their metadata, permissions, and help descriptions.
This makes Muditor the source of truth for command definitions.
"""

import click
from prisma import Prisma


# Command categories matching the Prisma enum
class Category:
    MOVEMENT = "MOVEMENT"
    COMBAT = "COMBAT"
    COMMUNICATION = "COMMUNICATION"
    OBJECT = "OBJECT"
    INFORMATION = "INFORMATION"
    SOCIAL = "SOCIAL"
    ADMIN = "ADMIN"
    BUILDING = "BUILDING"
    SYSTEM = "SYSTEM"
    CLAN = "CLAN"
    MAGIC = "MAGIC"
    SKILLS = "SKILLS"


# All FieryMUD commands with metadata
COMMANDS = [
    # ============================================
    # MOVEMENT Commands
    # ============================================
    {
        "name": "north",
        "aliases": ["n"],
        "category": Category.MOVEMENT,
        "description": "Move north from your current location.",
        "usage": "north",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "south",
        "aliases": ["s"],
        "category": Category.MOVEMENT,
        "description": "Move south from your current location.",
        "usage": "south",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "east",
        "aliases": ["e"],
        "category": Category.MOVEMENT,
        "description": "Move east from your current location.",
        "usage": "east",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "west",
        "aliases": ["w"],
        "category": Category.MOVEMENT,
        "description": "Move west from your current location.",
        "usage": "west",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "up",
        "aliases": ["u"],
        "category": Category.MOVEMENT,
        "description": "Move up from your current location.",
        "usage": "up",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "down",
        "aliases": ["d"],
        "category": Category.MOVEMENT,
        "description": "Move down from your current location.",
        "usage": "down",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "enter",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Enter a portal, building, or other enterable object.",
        "usage": "enter [object]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "leave",
        "aliases": ["exit"],
        "category": Category.MOVEMENT,
        "description": "Leave a building or enclosed area.",
        "usage": "leave",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "follow",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Follow another character as they move.",
        "usage": "follow <character>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "group",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Form or manage a group with other players.",
        "usage": "group [player]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "ungroup",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Remove yourself or another player from a group.",
        "usage": "ungroup [player]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "open",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Open a door, container, or other openable object.",
        "usage": "open <door|container>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "close",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Close a door, container, or other closable object.",
        "usage": "close <door|container>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "lock",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Lock a door or container using an appropriate key.",
        "usage": "lock <door|container>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "unlock",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Unlock a door or container using an appropriate key.",
        "usage": "unlock <door|container>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "pick",
        "aliases": [],
        "category": Category.MOVEMENT,
        "description": "Attempt to pick a lock on a door or container.",
        "usage": "pick <door|container>",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # INFORMATION Commands
    # ============================================
    {
        "name": "look",
        "aliases": ["l"],
        "category": Category.INFORMATION,
        "description": "Look at your surroundings, an object, or a character.",
        "usage": "look [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "examine",
        "aliases": ["exa"],
        "category": Category.INFORMATION,
        "description": "Examine an object or character in detail.",
        "usage": "examine <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "score",
        "aliases": ["sc"],
        "category": Category.INFORMATION,
        "description": "Display your character's statistics and attributes.",
        "usage": "score",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "inventory",
        "aliases": ["i", "inv"],
        "category": Category.INFORMATION,
        "description": "List all items you are carrying.",
        "usage": "inventory",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "equipment",
        "aliases": ["eq"],
        "category": Category.INFORMATION,
        "description": "List all items you are currently wearing or wielding.",
        "usage": "equipment",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "who",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "List all players currently online.",
        "usage": "who [class|race|level]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "where",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "Find the location of a player or mob in the same zone.",
        "usage": "where [name]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "weather",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "Check the current weather conditions.",
        "usage": "weather",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "time",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "Check the current game time and date.",
        "usage": "time",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "help",
        "aliases": ["?"],
        "category": Category.INFORMATION,
        "description": "Get help on commands, spells, skills, and game concepts.",
        "usage": "help [topic]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "commands",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "List all available commands.",
        "usage": "commands",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "skills",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "List your character's skills and proficiency levels.",
        "usage": "skills",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "spells",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "List your character's known spells.",
        "usage": "spells",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "affects",
        "aliases": ["aff"],
        "category": Category.INFORMATION,
        "description": "List all magical effects currently affecting you.",
        "usage": "affects",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "consider",
        "aliases": ["con"],
        "category": Category.INFORMATION,
        "description": "Evaluate the difficulty of fighting a target.",
        "usage": "consider <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "scan",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "Scan nearby rooms for creatures and players.",
        "usage": "scan [direction]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "exits",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "List all visible exits from your current location.",
        "usage": "exits",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "areas",
        "aliases": [],
        "category": Category.INFORMATION,
        "description": "List all areas/zones in the game with level ranges.",
        "usage": "areas",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # COMMUNICATION Commands
    # ============================================
    {
        "name": "say",
        "aliases": ["'"],
        "category": Category.COMMUNICATION,
        "description": "Speak to everyone in your current room.",
        "usage": "say <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "tell",
        "aliases": [],
        "category": Category.COMMUNICATION,
        "description": "Send a private message to another player.",
        "usage": "tell <player> <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "reply",
        "aliases": [],
        "category": Category.COMMUNICATION,
        "description": "Reply to the last person who sent you a tell.",
        "usage": "reply <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "whisper",
        "aliases": [],
        "category": Category.COMMUNICATION,
        "description": "Whisper privately to someone in the same room.",
        "usage": "whisper <person> <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "shout",
        "aliases": [],
        "category": Category.COMMUNICATION,
        "description": "Shout a message to everyone in the same zone.",
        "usage": "shout <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "gossip",
        "aliases": ["gos"],
        "category": Category.COMMUNICATION,
        "description": "Send a message on the global gossip channel.",
        "usage": "gossip <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "auction",
        "aliases": ["auc"],
        "category": Category.COMMUNICATION,
        "description": "Advertise items for sale on the auction channel.",
        "usage": "auction <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "gsay",
        "aliases": ["gtell"],
        "category": Category.COMMUNICATION,
        "description": "Send a message to all members of your group.",
        "usage": "gsay <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "emote",
        "aliases": [":"],
        "category": Category.COMMUNICATION,
        "description": "Express an action or emotion to the room.",
        "usage": "emote <action>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "ooc",
        "aliases": [],
        "category": Category.COMMUNICATION,
        "description": "Send an out-of-character message on a global channel.",
        "usage": "ooc <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "newbie",
        "aliases": [],
        "category": Category.COMMUNICATION,
        "description": "Send a message on the newbie help channel.",
        "usage": "newbie <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # OBJECT Commands
    # ============================================
    {
        "name": "get",
        "aliases": ["g", "take"],
        "category": Category.OBJECT,
        "description": "Pick up an item from the ground or a container.",
        "usage": "get <item> [container]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "drop",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Drop an item from your inventory onto the ground.",
        "usage": "drop <item>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "put",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Put an item into a container.",
        "usage": "put <item> <container>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "give",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Give an item to another character.",
        "usage": "give <item> <character>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "wear",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Wear an item of clothing or armor.",
        "usage": "wear <item>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "wield",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Wield a weapon in your primary hand.",
        "usage": "wield <weapon>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "hold",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Hold an item in your hand.",
        "usage": "hold <item>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "remove",
        "aliases": ["rem"],
        "category": Category.OBJECT,
        "description": "Remove an item you are wearing.",
        "usage": "remove <item>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "eat",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Eat food to reduce hunger.",
        "usage": "eat <food>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "drink",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Drink from a beverage container or fountain.",
        "usage": "drink <container>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "fill",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Fill a container with liquid from a fountain.",
        "usage": "fill <container>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "pour",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Pour liquid from one container to another.",
        "usage": "pour <from> <to>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "quaff",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Drink a potion to gain its magical effects.",
        "usage": "quaff <potion>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "recite",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Read a scroll to cast its spell.",
        "usage": "recite <scroll> [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "use",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Use a wand, staff, or other magical item.",
        "usage": "use <item> [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "donate",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Donate an item to the donation room for other players.",
        "usage": "donate <item>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "junk",
        "aliases": [],
        "category": Category.OBJECT,
        "description": "Destroy an item permanently for a small gold reward.",
        "usage": "junk <item>",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # COMBAT Commands
    # ============================================
    {
        "name": "kill",
        "aliases": ["k", "hit"],
        "category": Category.COMBAT,
        "description": "Attack a creature or player to begin combat.",
        "usage": "kill <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "flee",
        "aliases": [],
        "category": Category.COMBAT,
        "description": "Attempt to flee from combat in a random direction.",
        "usage": "flee",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "retreat",
        "aliases": [],
        "category": Category.COMBAT,
        "description": "Attempt to flee from combat in a specific direction.",
        "usage": "retreat <direction>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "rescue",
        "aliases": [],
        "category": Category.COMBAT,
        "description": "Rescue an ally by taking their attacker's focus.",
        "usage": "rescue <ally>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "assist",
        "aliases": [],
        "category": Category.COMBAT,
        "description": "Join combat alongside an ally.",
        "usage": "assist <ally>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "wimpy",
        "aliases": [],
        "category": Category.COMBAT,
        "description": "Set HP threshold for automatic flee attempts.",
        "usage": "wimpy [hp]",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # SKILLS Commands (Combat Skills)
    # ============================================
    {
        "name": "kick",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Kick an opponent for extra damage.",
        "usage": "kick [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "bash",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Shield bash an opponent, potentially stunning them.",
        "usage": "bash [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "backstab",
        "aliases": ["bs"],
        "category": Category.SKILLS,
        "description": "Sneak behind an enemy for a devastating surprise attack.",
        "usage": "backstab <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "circle",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Circle behind an opponent in combat for a backstab.",
        "usage": "circle [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "disarm",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Attempt to disarm an opponent's weapon.",
        "usage": "disarm [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "trip",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Trip an opponent to knock them down.",
        "usage": "trip [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "sneak",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Move silently to avoid detection.",
        "usage": "sneak",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "hide",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Hide in shadows to avoid being seen.",
        "usage": "hide",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "steal",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Attempt to steal an item from a character.",
        "usage": "steal <item> <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "track",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Track a creature or player by their footprints.",
        "usage": "track <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "meditate",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Meditate to recover mana more quickly.",
        "usage": "meditate",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "bandage",
        "aliases": [],
        "category": Category.SKILLS,
        "description": "Bandage wounds to stop bleeding and restore HP.",
        "usage": "bandage [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # MAGIC Commands
    # ============================================
    {
        "name": "cast",
        "aliases": ["c"],
        "category": Category.MAGIC,
        "description": "Cast a spell on yourself, an ally, or an enemy.",
        "usage": "cast '<spell name>' [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "memorize",
        "aliases": ["mem"],
        "category": Category.MAGIC,
        "description": "Memorize a spell to prepare it for casting.",
        "usage": "memorize <spell>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "forget",
        "aliases": [],
        "category": Category.MAGIC,
        "description": "Forget a memorized spell to make room for others.",
        "usage": "forget <spell>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "pray",
        "aliases": [],
        "category": Category.MAGIC,
        "description": "Pray to your deity to prepare divine spells.",
        "usage": "pray <spell>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "chant",
        "aliases": [],
        "category": Category.MAGIC,
        "description": "Chant to channel magical energy.",
        "usage": "chant",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # POSITION Commands
    # ============================================
    {
        "name": "sit",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Sit down to rest.",
        "usage": "sit",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "stand",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Stand up from a sitting or resting position.",
        "usage": "stand",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "rest",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Rest to recover HP and mana faster.",
        "usage": "rest",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "sleep",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Sleep to recover HP and mana even faster.",
        "usage": "sleep",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "wake",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Wake up from sleeping.",
        "usage": "wake",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # SYSTEM Commands
    # ============================================
    {
        "name": "save",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Save your character to the database.",
        "usage": "save",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "quit",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Save and exit the game.",
        "usage": "quit",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "password",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Change your account password.",
        "usage": "password <old> <new>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "title",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Set your character's title.",
        "usage": "title <title>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "description",
        "aliases": ["desc"],
        "category": Category.SYSTEM,
        "description": "Set your character's description that others see when examining you.",
        "usage": "description",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "toggle",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Toggle various character preferences and settings.",
        "usage": "toggle [option]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "prompt",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Customize your command prompt display.",
        "usage": "prompt [format]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "color",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Toggle ANSI color display.",
        "usage": "color [on|off]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "brief",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Toggle brief room descriptions.",
        "usage": "brief",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "autoexit",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Toggle automatic exit display when entering rooms.",
        "usage": "autoexit",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "autoloot",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Toggle automatic looting of corpses.",
        "usage": "autoloot",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "autogold",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Toggle automatic gold collection from corpses.",
        "usage": "autogold",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "autosplit",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Toggle automatic gold splitting with group members.",
        "usage": "autosplit",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "alias",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Create command aliases for frequently used commands.",
        "usage": "alias [name] [command]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "practice",
        "aliases": ["prac"],
        "category": Category.SYSTEM,
        "description": "Practice skills at a guildmaster.",
        "usage": "practice [skill]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "train",
        "aliases": [],
        "category": Category.SYSTEM,
        "description": "Train attributes at a trainer.",
        "usage": "train [attribute]",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # CLAN Commands
    # ============================================
    {
        "name": "clan",
        "aliases": [],
        "category": Category.CLAN,
        "description": "View clan information and management commands.",
        "usage": "clan [subcommand]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "clansay",
        "aliases": ["csay", "c:"],
        "category": Category.CLAN,
        "description": "Send a message to all online clan members.",
        "usage": "clansay <message>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "clanwho",
        "aliases": [],
        "category": Category.CLAN,
        "description": "List all online members of your clan.",
        "usage": "clanwho",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "deposit",
        "aliases": [],
        "category": Category.CLAN,
        "description": "Deposit gold into your clan bank.",
        "usage": "deposit <amount>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "withdraw",
        "aliases": [],
        "category": Category.CLAN,
        "description": "Withdraw gold from your clan bank.",
        "usage": "withdraw <amount>",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # SOCIAL Commands (common ones)
    # ============================================
    {
        "name": "smile",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Smile at someone or the room.",
        "usage": "smile [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "nod",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Nod in agreement.",
        "usage": "nod [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "wave",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Wave at someone.",
        "usage": "wave [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "bow",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Bow respectfully.",
        "usage": "bow [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "laugh",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Laugh out loud.",
        "usage": "laugh [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "cry",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Cry sadly.",
        "usage": "cry [target]",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "hug",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Hug someone warmly.",
        "usage": "hug <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "poke",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Poke someone to get their attention.",
        "usage": "poke <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    {
        "name": "thank",
        "aliases": [],
        "category": Category.SOCIAL,
        "description": "Thank someone.",
        "usage": "thank <target>",
        "immortalOnly": False,
        "permissions": [],
    },
    # ============================================
    # ADMIN Commands (Immortal Only)
    # ============================================
    {
        "name": "goto",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Teleport to a room, player, or mobile.",
        "usage": "goto <room|player|mobile>",
        "immortalOnly": True,
        "permissions": ["can_goto"],
    },
    {
        "name": "transfer",
        "aliases": ["trans"],
        "category": Category.ADMIN,
        "description": "Transfer a player or mobile to your location.",
        "usage": "transfer <target> [location]",
        "immortalOnly": True,
        "permissions": ["can_transfer"],
    },
    {
        "name": "at",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Execute a command at a remote location.",
        "usage": "at <location> <command>",
        "immortalOnly": True,
        "permissions": ["can_at"],
    },
    {
        "name": "echo",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Send a message to everyone in a room or zone.",
        "usage": "echo <message>",
        "immortalOnly": True,
        "permissions": ["can_echo"],
    },
    {
        "name": "send",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Send a private message to a player.",
        "usage": "send <player> <message>",
        "immortalOnly": True,
        "permissions": ["can_send"],
    },
    {
        "name": "load",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Load a mobile or object into the game.",
        "usage": "load mob|obj <vnum>",
        "immortalOnly": True,
        "permissions": ["can_load"],
    },
    {
        "name": "purge",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Remove objects and mobiles from a room.",
        "usage": "purge [target]",
        "immortalOnly": True,
        "permissions": ["can_purge"],
    },
    {
        "name": "zreset",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Reset a zone to its original state.",
        "usage": "zreset [zone]",
        "immortalOnly": True,
        "permissions": ["can_zreset"],
    },
    {
        "name": "advance",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Advance a player to a higher level.",
        "usage": "advance <player> <level>",
        "immortalOnly": True,
        "permissions": ["can_advance"],
    },
    {
        "name": "restore",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Restore a player's HP, mana, and moves to full.",
        "usage": "restore <player>",
        "immortalOnly": True,
        "permissions": ["can_restore"],
    },
    {
        "name": "set",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Set attributes on players, mobiles, or rooms.",
        "usage": "set <type> <target> <field> <value>",
        "immortalOnly": True,
        "permissions": ["can_set"],
    },
    {
        "name": "snoop",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Monitor all commands entered by a player.",
        "usage": "snoop <player>",
        "immortalOnly": True,
        "permissions": ["can_snoop"],
    },
    {
        "name": "invis",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Toggle immortal invisibility.",
        "usage": "invis [level]",
        "immortalOnly": True,
        "permissions": ["can_invis"],
    },
    {
        "name": "holylight",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Toggle the ability to see in darkness and through invisibility.",
        "usage": "holylight",
        "immortalOnly": True,
        "permissions": ["can_holylight"],
    },
    {
        "name": "freeze",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Freeze a player, preventing all commands.",
        "usage": "freeze <player>",
        "immortalOnly": True,
        "permissions": ["can_freeze"],
    },
    {
        "name": "thaw",
        "aliases": ["unfreeze"],
        "category": Category.ADMIN,
        "description": "Unfreeze a frozen player.",
        "usage": "thaw <player>",
        "immortalOnly": True,
        "permissions": ["can_unfreeze"],
    },
    {
        "name": "dc",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Disconnect a player from the game.",
        "usage": "dc <player>",
        "immortalOnly": True,
        "permissions": ["can_dc"],
    },
    {
        "name": "force",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Force a player or mobile to execute a command.",
        "usage": "force <target> <command>",
        "immortalOnly": True,
        "permissions": ["can_force"],
    },
    {
        "name": "switch",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Switch into the body of a mobile.",
        "usage": "switch <mobile>",
        "immortalOnly": True,
        "permissions": ["can_switch"],
    },
    {
        "name": "return",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Return to your original body after switching.",
        "usage": "return",
        "immortalOnly": True,
        "permissions": ["can_switch"],
    },
    {
        "name": "page",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Page a player with an important message.",
        "usage": "page <player> <message>",
        "immortalOnly": True,
        "permissions": ["can_page"],
    },
    {
        "name": "ban",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Ban a site from connecting to the MUD.",
        "usage": "ban <site>",
        "immortalOnly": True,
        "permissions": ["can_ban"],
    },
    {
        "name": "unban",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Remove a site ban.",
        "usage": "unban <site>",
        "immortalOnly": True,
        "permissions": ["can_unban"],
    },
    {
        "name": "mute",
        "aliases": ["squelch"],
        "category": Category.ADMIN,
        "description": "Mute a player from using communication channels.",
        "usage": "mute <player>",
        "immortalOnly": True,
        "permissions": ["can_mute"],
    },
    {
        "name": "unmute",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Unmute a muted player.",
        "usage": "unmute <player>",
        "immortalOnly": True,
        "permissions": ["can_unmute"],
    },
    {
        "name": "wizlock",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Lock the game to prevent new connections.",
        "usage": "wizlock [level]",
        "immortalOnly": True,
        "permissions": ["can_wizlock"],
    },
    {
        "name": "shutdown",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Shut down the MUD server.",
        "usage": "shutdown [reboot|die]",
        "immortalOnly": True,
        "permissions": ["can_shutdown"],
    },
    {
        "name": "reboot",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Reboot the MUD server.",
        "usage": "reboot",
        "immortalOnly": True,
        "permissions": ["can_reboot"],
    },
    {
        "name": "copyover",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Hot reboot the MUD without disconnecting players.",
        "usage": "copyover",
        "immortalOnly": True,
        "permissions": ["can_copyover"],
    },
    {
        "name": "syslog",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "View or toggle system log level.",
        "usage": "syslog [level]",
        "immortalOnly": True,
        "permissions": ["can_syslog"],
    },
    {
        "name": "wiznet",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Toggle wiznet channel visibility.",
        "usage": "wiznet [on|off]",
        "immortalOnly": True,
        "permissions": ["can_wiznet"],
    },
    {
        "name": "wizhelp",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "View help for immortal commands.",
        "usage": "wizhelp [topic]",
        "immortalOnly": True,
        "permissions": ["can_wizhelp"],
    },
    {
        "name": "stat",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "View detailed statistics on a room, mobile, object, or player.",
        "usage": "stat <type> <target>",
        "immortalOnly": True,
        "permissions": ["can_stat"],
    },
    {
        "name": "vnum",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Search for mobiles or objects by name.",
        "usage": "vnum mob|obj <name>",
        "immortalOnly": True,
        "permissions": ["can_vnum"],
    },
    {
        "name": "show",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "Show various game statistics and information.",
        "usage": "show <type>",
        "immortalOnly": True,
        "permissions": ["can_show"],
    },
    {
        "name": "users",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "List all connected users and their connection info.",
        "usage": "users",
        "immortalOnly": True,
        "permissions": ["can_users"],
    },
    {
        "name": "last",
        "aliases": [],
        "category": Category.ADMIN,
        "description": "View last login information for a player.",
        "usage": "last <player>",
        "immortalOnly": True,
        "permissions": ["can_last"],
    },
    # ============================================
    # BUILDING Commands (OLC)
    # ============================================
    {
        "name": "olc",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "Enter Online Creation mode.",
        "usage": "olc",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "redit",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "Edit room properties.",
        "usage": "redit [vnum]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "medit",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "Edit mobile (NPC) properties.",
        "usage": "medit [vnum]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "oedit",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "Edit object properties.",
        "usage": "oedit [vnum]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "zedit",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "Edit zone properties and resets.",
        "usage": "zedit [zone]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "sedit",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "Edit shop properties.",
        "usage": "sedit [vnum]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "tedit",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "Edit trigger/script properties.",
        "usage": "tedit [vnum]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "dig",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "Create a new room connected to the current one.",
        "usage": "dig <direction> [vnum]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "rlist",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "List rooms in a zone.",
        "usage": "rlist [zone]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "mlist",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "List mobiles in a zone.",
        "usage": "mlist [zone]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "olist",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "List objects in a zone.",
        "usage": "olist [zone]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "tlist",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "List triggers in a zone.",
        "usage": "tlist [zone]",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
    {
        "name": "zlist",
        "aliases": [],
        "category": Category.BUILDING,
        "description": "List all zones.",
        "usage": "zlist",
        "immortalOnly": True,
        "permissions": ["can_olc"],
    },
]


class CommandSeeder:
    """Seeds command definitions into the Command table."""

    def __init__(self, prisma: Prisma):
        self.prisma = prisma

    async def seed_commands(self, verbose: bool = False) -> dict:
        """Seed all command definitions.

        Args:
            verbose: Show detailed output

        Returns:
            Statistics dict with created/updated counts
        """
        stats = {"created": 0, "updated": 0, "skipped": 0, "total": 0}

        for cmd in COMMANDS:
            # Check if command already exists
            existing = await self.prisma.command.find_unique(
                where={"name": cmd["name"]}
            )

            if existing:
                # Update existing command
                await self.prisma.command.update(
                    where={"name": cmd["name"]},
                    data={
                        "aliases": cmd["aliases"],
                        "category": cmd["category"],
                        "description": cmd.get("description"),
                        "usage": cmd.get("usage"),
                        "immortalOnly": cmd["immortalOnly"],
                        "permissions": cmd["permissions"],
                    },
                )
                stats["updated"] += 1
                if verbose:
                    click.echo(f"    Updated: {cmd['name']}")
            else:
                # Create new command
                await self.prisma.command.create(
                    data={
                        "name": cmd["name"],
                        "aliases": cmd["aliases"],
                        "category": cmd["category"],
                        "description": cmd.get("description"),
                        "usage": cmd.get("usage"),
                        "immortalOnly": cmd["immortalOnly"],
                        "permissions": cmd["permissions"],
                    }
                )
                stats["created"] += 1
                if verbose:
                    click.echo(f"    Created: {cmd['name']}")

            stats["total"] += 1

        return stats

    async def get_command_count(self) -> int:
        """Get the count of commands in the database."""
        return await self.prisma.command.count()
