"""Content tables seeder: hard-coded fierymud-rs content moved into the database.

The Rust runtime used to carry these as compile-time arrays; builders now edit
them in Muditor and the game loads them at boot (data over code). Source of truth
for the seed rows is ``data/content_tables.json``::

    status_flag_values  [flag, ai_value]            -> "StatusFlagValue"
    spell_syllables     [syllable, replacement]     -> "SpellSyllable" (list order = sort_order)
    system_messages     {key, category, messages}   -> "SystemMessage"
    game_config         {category, key, ...}        -> "GameConfig" (JSON-typed value)
    prompt_letters      [letter, [Ability.plain_name]] -> "Ability".prompt_letter

Rows are only ever added: an existing row is left alone so builder edits survive a
re-seed. ``prompt_letter`` is only set where it is still NULL. An idempotent SQL
equivalent for already-seeded databases is generated by :func:`build_sql` into
``data/sql/2026-10-09-content-tables.sql`` (a unit test keeps the two in sync).
"""

import json
from pathlib import Path

from prisma import Prisma

CONTENT_JSON = Path(__file__).resolve().parents[3] / "data" / "content_tables.json"


def load_content() -> dict:
    """The parsed ``data/content_tables.json``."""
    with open(CONTENT_JSON, encoding="utf-8") as f:
        return json.load(f)


def _lit(value) -> str:
    """SQL literal for a str / int / None."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _values(rows: list[str]) -> str:
    return ",\n".join(f"  {r}" for r in rows)


def config_value_text(row: dict) -> str:
    """The text stored in ``GameConfig.value`` for a content row."""
    value = row["value"]
    if row["valueType"] == "JSON":
        return json.dumps(value, ensure_ascii=False)
    return str(value)


DDL = [
    """CREATE TABLE IF NOT EXISTS "StatusFlagValue" (
    "flag" TEXT NOT NULL,
    "ai_value" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "StatusFlagValue_pkey" PRIMARY KEY ("flag")
)""",
    """CREATE TABLE IF NOT EXISTS "SpellSyllable" (
    "id" SERIAL NOT NULL,
    "sort_order" INTEGER NOT NULL,
    "syllable" TEXT NOT NULL,
    "replacement" TEXT NOT NULL,

    CONSTRAINT "SpellSyllable_pkey" PRIMARY KEY ("id")
)""",
    'CREATE UNIQUE INDEX IF NOT EXISTS "SpellSyllable_syllable_key" ON "SpellSyllable"("syllable")',
    'CREATE INDEX IF NOT EXISTS "SpellSyllable_sort_order_idx" ON "SpellSyllable"("sort_order")',
    'ALTER TABLE "Ability" ADD COLUMN IF NOT EXISTS "prompt_letter" VARCHAR(1)',
]


def build_statements(content: dict | None = None) -> list[str]:
    """Every statement of the patch, in order, without BEGIN/COMMIT or trailing semicolons."""
    c = load_content() if content is None else content
    out = list(DDL)

    rows = [f"({_lit(f)}, {_lit(v)})" for f, v in c["status_flag_values"]]
    out.append(
        'INSERT INTO "StatusFlagValue" ("flag", "ai_value") VALUES\n'
        + _values(rows)
        + '\nON CONFLICT ("flag") DO NOTHING'
    )

    rows = [f"({i}, {_lit(s)}, {_lit(r)})" for i, (s, r) in enumerate(c["spell_syllables"], start=1)]
    out.append(
        'INSERT INTO "SpellSyllable" ("sort_order", "syllable", "replacement") VALUES\n'
        + _values(rows)
        + '\nON CONFLICT ("syllable") DO NOTHING'
    )

    rows = []
    for m in c["system_messages"]:
        arr = ", ".join(_lit(x) for x in m["messages"])
        rows.append(f"({_lit(m['key'])}, {_lit(m['category'])}, ARRAY[{arr}]::text[], CURRENT_TIMESTAMP)")
    out.append(
        'INSERT INTO "SystemMessage" ("key", "category", "messages", "updated_at") VALUES\n'
        + _values(rows)
        + '\nON CONFLICT ("key") DO NOTHING'
    )

    rows = []
    for g in c["game_config"]:
        rows.append(
            f"({_lit(g['category'])}, {_lit(g['key'])}, {_lit(config_value_text(g))}, "
            f"'{g['valueType']}'::\"ConfigValueType\", {_lit(g.get('description'))}, CURRENT_TIMESTAMP)"
        )
    out.append(
        'INSERT INTO "GameConfig" ("category", "key", "value", "value_type", "description", "updated_at") VALUES\n'
        + _values(rows)
        + '\nON CONFLICT ("category", "key") DO NOTHING'
    )

    rows = [f"({_lit(letter)}, {_lit(name)})" for letter, names in c["prompt_letters"] for name in names]
    out.append(
        'UPDATE "Ability" a\nSET "prompt_letter" = v.letter\nFROM (VALUES\n'
        + _values(rows)
        + '\n) AS v(letter, plain_name)\nWHERE a.plain_name = v.plain_name AND a."prompt_letter" IS NULL'
    )
    return out


def build_sql(content: dict | None = None) -> str:
    """The idempotent SQL patch, equivalent to :meth:`ContentTablesSeeder.seed_content_tables`."""
    body = ";\n\n".join(build_statements(content))
    return f"""-- Content tables: hard-coded fierymud-rs content moved into the database (data over code).
--
--   "StatusFlagValue"  AI worth of each status flag (mob_ai value_status_flag: what a
--                      monster thinks a piece of gear is worth). Flags without a row score 0.
--   "SystemMessage"    exp_progress (the eleven `%E` prompt lines, indexed by tenth of the
--                      level), insult_lines (the `insult` command), month_names (the sixteen
--                      calendar months), weather_change_<precip> (the line sent when a zone's
--                      precipitation changes; several messages = random pick).
--   "GameConfig"       display.prompt_templates: JSON [[name, template], ...] for `prompt list`.
--   "SpellSyllable"    spell chant gibberish (legacy syllable table); sort_order is match order.
--   "Ability"          prompt_letter: the `%d<letter>` prompt cooldown bar each ability drives.
--
-- Keyed by Ability.plain_name / natural keys, so ids may differ per database. The game logs
-- an ERROR and falls back to empty text when a table or column is missing, so applying this
-- by hand after the deploy is safe.
--
-- Idempotent and builder-safe: tables are created IF NOT EXISTS, rows are inserted only when
-- missing (ON CONFLICT DO NOTHING), prompt_letter is only set where still NULL. A second run
-- changes 0 rows. Keep in sync with the Prisma models StatusFlagValue / SpellSyllable and
-- Ability.promptLetter in muditor/packages/db/prisma/schema.prisma. Generated from
-- data/content_tables.json; a unit test keeps the two in sync.

BEGIN;

{body};

COMMIT;
"""


class ContentTablesSeeder:
    """Adds the missing content rows; existing rows are left untouched."""

    def __init__(self, prisma: Prisma):
        self.prisma = prisma

    async def seed_content_tables(self, verbose: bool = False) -> dict:
        """Run every statement of the patch. Returns rows touched per statement."""
        stats = {"statements": 0, "rows": 0}
        for stmt in build_statements():
            n = await self.prisma.execute_raw(stmt)
            stats["statements"] += 1
            stats["rows"] += n or 0
            if verbose:
                print(f"  {stmt.splitlines()[0][:70]}: {n}")
        return stats
