"""Creation recipe seeder (Minor Creation keywords, Create Food by class).

Legacy hard-coded both: ``minor_creation_items[]`` (constants.cpp) mapped the
typed word to object ``1000 + index``, and ``spell_creations`` (magic.cpp)
picked Create Food's zone from the caster class. The game now reads them from
the ``CreationRecipe`` table, seeded here from ``data/creation_recipes.json``::

    {"ability": "MINOR_CREATION", "keyword": "dagger", "class": null,
     "object": {"zone": 10, "id": 12}}
    {"ability": "CREATE_FOOD", "keyword": null, "class": "Priest",
     "object": {"zone": 100, "id": null}}

``ability`` is ``Ability.plain_name`` and ``class`` is ``Class.plain_name``, so
the rows survive an id renumbering. ``object.id`` null means "any FOOD object
in that zone". Rows are only ever added: an existing (ability, keyword, class)
row is left alone so builder edits survive a re-seed.

Run after the abilities and classes are seeded. An idempotent SQL equivalent
for already-seeded databases is generated by :func:`build_sql` into
``data/sql/2026-10-09-creation-recipes.sql``.
"""

import json
from pathlib import Path

from prisma import Prisma

RECIPES_JSON = Path(__file__).resolve().parents[3] / "data" / "creation_recipes.json"

# The row INSERT shared by the seeder (parameters $1..$6) and the SQL patch
# (VALUES rows). NOT EXISTS rather than ON CONFLICT: Postgres treats NULLs in
# the (ability_id, keyword, class_id) unique index as distinct.
_COLUMNS = "ability_id, keyword, class_id, object_zone_id, object_id"


def load_recipes() -> list[dict]:
    """The recipe entries from ``data/creation_recipes.json``, in insert order."""
    with open(RECIPES_JSON, encoding="utf-8") as f:
        return json.load(f)["recipes"]


def _lit(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _values_row(ord_: int, r: dict) -> str:
    ability = _lit(r["ability"])
    keyword = _lit(r.get("keyword")) if r.get("keyword") is not None else "NULL::text"
    cls = _lit(r.get("class")) if r.get("class") is not None else "NULL::text"
    obj = r["object"]
    obj_id = _lit(obj["id"]) if obj.get("id") is not None else "NULL::int"
    return f"    ({ord_}, {ability}, {keyword}, {cls}, {obj['zone']}, {obj_id})"


def build_sql(recipes: list[dict] | None = None) -> str:
    """Idempotent SQL patch equivalent to :meth:`CreationRecipeSeeder.seed_creation_recipes`."""
    recipes = load_recipes() if recipes is None else recipes
    rows = ",\n".join(_values_row(i, r) for i, r in enumerate(recipes, start=1))
    return f'''-- CreationRecipe: what the creation spells conjure, moved out of the hard-coded
-- tables in fierymud-rs commands.rs (data over code).
--
--   MINOR_CREATION  one row per keyword (legacy minor_creation_items[] in
--                   constants.cpp; vnum 1000+i = zone 10 id i). The game matches
--                   the typed word as an abbreviation in `id` order, so the rows
--                   are inserted in legacy order.
--   CREATE_FOOD     one row per caster class (legacy spell_creations in
--                   magic.cpp: Priest 100, Paladin 110, Anti-Paladin 130,
--                   Druid 140, everyone else 120). object_id NULL = any FOOD
--                   object in that zone, picked by the caster's skill.
--
-- Keyed by Ability.plain_name / Class.plain_name, so ids may differ per database.
-- Also pins Create Food's fallback object (waybread, zone 185 id 8) in the
-- ability's `create` effect params, used when a class zone has no FOOD loaded.
--
-- Idempotent and builder-safe: the table is created IF NOT EXISTS, a row is
-- inserted only when no row exists for its (ability, keyword, class), and the
-- params merge never overrides a value already set. A second run changes
-- nothing. Keep in sync with the Prisma model CreationRecipe in
-- muditor/packages/db/prisma/schema.prisma. Generated from
-- data/creation_recipes.json; a unit test keeps the two in sync.

BEGIN;

CREATE TABLE IF NOT EXISTS "CreationRecipe" (
    "id" SERIAL NOT NULL,
    "ability_id" INTEGER NOT NULL,
    "keyword" TEXT,
    "class_id" INTEGER,
    "object_zone_id" INTEGER NOT NULL,
    "object_id" INTEGER,

    CONSTRAINT "CreationRecipe_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "CreationRecipe_ability_id_fkey" FOREIGN KEY ("ability_id") REFERENCES "Ability"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CreationRecipe_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "Class"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "CreationRecipe_ability_id_keyword_class_id_key"
    ON "CreationRecipe"("ability_id", "keyword", "class_id");

INSERT INTO "CreationRecipe" ({_COLUMNS})
SELECT a.id, v.keyword, c.id, v.zone, v.obj
FROM (VALUES
{rows}
) AS v(ord, ability, keyword, class_name, zone, obj)
JOIN "Ability" a ON a.plain_name = v.ability
LEFT JOIN "Class" c ON c.plain_name = v.class_name
WHERE (v.class_name IS NULL OR c.id IS NOT NULL)
  AND NOT EXISTS (
      SELECT 1 FROM "CreationRecipe" r
      WHERE r.ability_id = a.id
        AND r.keyword IS NOT DISTINCT FROM v.keyword
        AND r.class_id IS NOT DISTINCT FROM c.id
  )
ORDER BY v.ord;

UPDATE "AbilityEffect" ae
SET override_params =
      '{{"objectZoneId": 185, "objectId": 8}}'::jsonb || COALESCE(ae.override_params, '{{}}'::jsonb)
FROM "Ability" a, "Effect" e
WHERE ae.ability_id = a.id
  AND ae.effect_id = e.id
  AND a.plain_name = 'CREATE_FOOD'
  AND e."effectType" = 'create'
  AND NOT (COALESCE(ae.override_params, '{{}}'::jsonb) ?& ARRAY['objectZoneId', 'objectId']);

COMMIT;
'''


# One recipe row per statement; $1 ability plain_name, $2 keyword, $3 class
# plain_name, $4 object zone, $5 object id.
_INSERT_ROW = f"""
INSERT INTO "CreationRecipe" ({_COLUMNS})
SELECT a.id, $2::text, c.id, $4::int, $5::int
FROM "Ability" a
LEFT JOIN "Class" c ON c.plain_name = $3::text
WHERE a.plain_name = $1::text
  AND ($3::text IS NULL OR c.id IS NOT NULL)
  AND NOT EXISTS (
      SELECT 1 FROM "CreationRecipe" r
      WHERE r.ability_id = a.id
        AND r.keyword IS NOT DISTINCT FROM $2::text
        AND r.class_id IS NOT DISTINCT FROM c.id
  )
"""


class CreationRecipeSeeder:
    """Inserts the ``CreationRecipe`` rows; existing rows are left untouched."""

    def __init__(self, prisma: Prisma):
        self.prisma = prisma

    async def seed_creation_recipes(self, verbose: bool = False) -> dict:
        """Add every missing recipe row. Returns counts."""
        stats = {"inserted": 0, "existing": 0, "total": 0}
        for r in load_recipes():
            stats["total"] += 1
            obj = r["object"]
            n = await self.prisma.execute_raw(
                _INSERT_ROW,
                r["ability"],
                r.get("keyword"),
                r.get("class"),
                obj["zone"],
                obj.get("id"),
            )
            if n:
                stats["inserted"] += 1
            else:
                stats["existing"] += 1
            if verbose:
                label = r.get("keyword") or r.get("class") or "default"
                print(f"  {r['ability']} {label}: {'added' if n else 'kept'}")
        return stats
