"""Recall scroll destination seeder.

Legacy scrolls of recall (fierymud_legacy/src/spec_procs.cpp ``do_recall`` and
``{red,green,blue,gray}_recall_room``) sent the reader to the guild hall of
their class in the scroll's town. The legacy code hard-coded the table; here it
lives in ``data/recall_scrolls.json`` and is written into each scroll's
``Objects.values["Recall Rooms"]`` so the game reads it from the database::

    {"Recall Rooms": {"default": {"zone": 30, "id": 22},
                      "classes": {"sorcerer": {"zone": 30, "id": 46}, ...}}}

Class keys are lowercased ``Class.plain_name``; the game falls back to the
reader's parent class and then to ``default``.

Run after the world import (the import rewrites ``values``). An idempotent SQL
equivalent for already-seeded databases is generated by
:func:`build_sql` into ``data/sql/2026-10-07-recall-scroll-rooms.sql``.
"""

import json
from pathlib import Path

from prisma import Json, Prisma

RECALL_SCROLLS_JSON = Path(__file__).resolve().parents[3] / "data" / "recall_scrolls.json"
VALUES_KEY = "Recall Rooms"


def load_scrolls() -> list[dict]:
    """The scroll entries from ``data/recall_scrolls.json``."""
    with open(RECALL_SCROLLS_JSON, encoding="utf-8") as f:
        return json.load(f)["scrolls"]


def build_sql(scrolls: list[dict] | None = None) -> str:
    """Idempotent SQL patch equivalent to :meth:`RecallScrollSeeder.seed_recall_scrolls`."""
    scrolls = load_scrolls() if scrolls is None else scrolls
    lines = [
        '-- Scroll-of-recall destinations (Refs fierymud-rs #12).',
        '--',
        '-- Brings an already-seeded database in line with `fierylib seed recall-scrolls`',
        '-- without a reimport: sets "Objects"."values"."Recall Rooms" on the four coloured',
        '-- recall scrolls (legacy spec_procs.cpp {red,green,blue,gray}_recall_room).',
        '-- Idempotent: the jsonb || replaces just that one key; rerunning is a no-op.',
        '-- Generated from data/recall_scrolls.json; a unit test keeps the two in sync.',
        '',
        'BEGIN;',
        '',
    ]
    for s in scrolls:
        payload = json.dumps({VALUES_KEY: s["recall_rooms"]}, sort_keys=True)
        lines.append(f"-- {s['colour']} scroll of recall (legacy vnum {s['legacy_vnum']})")
        lines.append('UPDATE "Objects"')
        lines.append(f"SET \"values\" = \"values\" || '{payload}'::jsonb, updated_at = now()")
        lines.append(
            f"WHERE zone_id = {s['object']['zone']} AND id = {s['object']['id']} AND type = 'SCROLL';"
        )
        lines.append("")
    lines.append("COMMIT;")
    return "\n".join(lines) + "\n"


class RecallScrollSeeder:
    """Writes ``Objects.values["Recall Rooms"]`` for the coloured recall scrolls."""

    def __init__(self, prisma: Prisma):
        self.prisma = prisma

    async def seed_recall_scrolls(self, verbose: bool = False) -> dict:
        """Merge the recall table into each scroll's ``values``. Returns counts."""
        stats = {"updated": 0, "missing": 0, "total": 0}
        for s in load_scrolls():
            stats["total"] += 1
            where = {"zoneId_id": {"zoneId": s["object"]["zone"], "id": s["object"]["id"]}}
            obj = await self.prisma.objects.find_unique(where=where)
            if obj is None:
                stats["missing"] += 1
                if verbose:
                    print(f"  scroll {s['object']['zone']}:{s['object']['id']} not found, skipped")
                continue
            values = obj.values
            if isinstance(values, str):
                values = json.loads(values)
            merged = {**(values or {}), VALUES_KEY: s["recall_rooms"]}
            await self.prisma.objects.update(where=where, data={"values": Json(merged)})
            stats["updated"] += 1
            if verbose:
                print(f"  {s['colour']} scroll {s['object']['zone']}:{s['object']['id']} updated")
        return stats
