-- RaceEffects: innate (permanent) race effects as real status flags.
--
-- The old importer linked each race to the generic `status` Effect with empty
-- modifier_data ({}); the runtime would have read that as the Effect default flag
-- (`bless`). Now each race has ONE row (the table is unique on race+effect):
-- effect = `status`, modifier_data = {"flags": [<status flag>, ...]}, built from the
-- legacy PERM_EFF(RACE_x, EFF_y) table in fierymud_legacy/src/races.cpp (init_races)
-- via the MobDefaultEffects mapping (EFF_INFRAVISION -> infravision, EFF_SENSE_LIFE ->
-- detect_life, ...). Also adds HALF_ELF, whose row the importer used to drop.
-- Generated by scripts/gen_race_effects_sql.py from data/races.json. 24 races.
--
-- Idempotent and builder-safe: only rows still in the placeholder shape
-- (modifier_data = '{}') are rewritten; any row a builder already edited is left
-- alone, and a second run changes nothing. Leftover placeholder rows for races with
-- no innate effects are removed.

BEGIN;

INSERT INTO "RaceEffects" (race, effect_id, strength, modifier_data)
SELECT v.race::"Race", e.id, 1, v.flags::jsonb
FROM (VALUES
    ('BROWNIE', '{"flags": ["infravision"]}'),
    ('DRAGONBORN_ACID', '{"flags": ["infravision"]}'),
    ('DRAGONBORN_FIRE', '{"flags": ["infravision"]}'),
    ('DRAGONBORN_FROST', '{"flags": ["infravision"]}'),
    ('DRAGONBORN_GAS', '{"flags": ["infravision"]}'),
    ('DRAGONBORN_LIGHTNING', '{"flags": ["infravision"]}'),
    ('DRAGON_ACID', '{"flags": ["fly"]}'),
    ('DRAGON_FIRE', '{"flags": ["fly"]}'),
    ('DRAGON_FROST', '{"flags": ["fly"]}'),
    ('DRAGON_GAS', '{"flags": ["fly"]}'),
    ('DRAGON_GENERAL', '{"flags": ["fly"]}'),
    ('DRAGON_LIGHTNING', '{"flags": ["fly"]}'),
    ('DROW', '{"flags": ["infravision", "ultravision"]}'),
    ('DUERGAR', '{"flags": ["infravision", "ultravision"]}'),
    ('DWARF', '{"flags": ["detect_poison", "infravision", "ultravision"]}'),
    ('ELF', '{"flags": ["infravision"]}'),
    ('FAERIE_SEELIE', '{"flags": ["fly"]}'),
    ('FAERIE_UNSEELIE', '{"flags": ["fly"]}'),
    ('GNOME', '{"flags": ["infravision"]}'),
    ('HALFLING', '{"flags": ["detect_life", "infravision"]}'),
    ('HALF_ELF', '{"flags": ["infravision"]}'),
    ('OGRE', '{"flags": ["infravision", "ultravision"]}'),
    ('SVERFNEBLIN', '{"flags": ["infravision", "ultravision"]}'),
    ('TROLL', '{"flags": ["infravision", "ultravision"]}')
) AS v(race, flags)
JOIN "Effect" e ON e.name = 'status'
ON CONFLICT (race, effect_id) DO UPDATE
    SET modifier_data = EXCLUDED.modifier_data
    WHERE "RaceEffects".modifier_data = '{}'::jsonb;

DELETE FROM "RaceEffects" re
USING "Effect" e
WHERE re.effect_id = e.id AND e.name = 'status' AND re.modifier_data = '{}'::jsonb;

COMMIT;
