-- Mob AI: race rules (dragon / demon breath, sweep, roar), WP-D of ops/plans/mob-ai.md.
--
-- Legacy dragonlike_attack (mobact.cpp): roll = rand(0, 150 - level); breath if roll < 5, sweep if
-- roll < 10, roar if roll < 15, for the DRAGON_* / DRAGONBORN_* races and DEMON. The element comes
-- from the body composition (earth/stone acid, air/ether lightning, fire/lava fire, water/ice/mist
-- frost, metal/bone/plant gas), any other composition rolls it. The rules express the bands with the
-- level_roll condition (one shared roll per mob per round) and the element with composition /
-- not_composition.
--
--   1. creates "RaceAiRules" (matches muditor packages/db/prisma/schema.prisma, db push compatible),
--   2. adds the RaceAbilities rows the races lack (legacy races.cpp assign_race_skills): the DRAGON_*
--      races and DEMON had no BREATHE_* / SWEEP / ROAR row; DRAGONBORN_* already have their breath,
--   3. seeds the rules.
-- Generated by `python -m fierylib.seeders.mob_ai_seeder --write-sql` from data/mob_ai_seed.json; a
-- unit test keeps the two in sync. Standalone (own table); the server reads it only with
-- mob_ai.enabled on. Keyed by Races.race (enum) and Ability.plain_name, never numeric ids. Insert
-- only if missing: builder edits survive and a second run changes 0 rows.

BEGIN;

CREATE TABLE IF NOT EXISTS "RaceAiRules" (
    "id" SERIAL NOT NULL,
    "race" "Race" NOT NULL,
    "ability_id" INTEGER NOT NULL,
    "priority" INTEGER NOT NULL,
    "chance_pct" INTEGER NOT NULL DEFAULT 100,
    "cooldown_s" INTEGER NOT NULL DEFAULT 0,
    "conditions" JSONB,
    "target" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "RaceAiRules_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "RaceAiRules_race_idx" ON "RaceAiRules"("race");

CREATE UNIQUE INDEX IF NOT EXISTS "RaceAiRules_race_ability_id_priority_key"
    ON "RaceAiRules"("race", "ability_id", "priority");

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'RaceAiRules_race_fkey') THEN
        ALTER TABLE "RaceAiRules" ADD CONSTRAINT "RaceAiRules_race_fkey"
            FOREIGN KEY ("race") REFERENCES "Races"("race") ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'RaceAiRules_ability_id_fkey') THEN
        ALTER TABLE "RaceAiRules" ADD CONSTRAINT "RaceAiRules_ability_id_fkey"
            FOREIGN KEY ("ability_id") REFERENCES "Ability"("id") ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
END
$$;

INSERT INTO "RaceAbilities" (race, ability_id, category, bonus, proficiency_cap)
SELECT v.race::"Race", a.id, 'PRIMARY', 0, 100
FROM (VALUES
    ('DRAGON_GENERAL', 'BREATHE_FIRE'),
    ('DRAGON_GENERAL', 'BREATHE_GAS'),
    ('DRAGON_GENERAL', 'BREATHE_FROST'),
    ('DRAGON_GENERAL', 'BREATHE_ACID'),
    ('DRAGON_GENERAL', 'BREATHE_LIGHTNING'),
    ('DRAGON_GENERAL', 'SWEEP'),
    ('DRAGON_GENERAL', 'ROAR'),
    ('DEMON', 'BREATHE_FIRE'),
    ('DEMON', 'BREATHE_GAS'),
    ('DEMON', 'BREATHE_FROST'),
    ('DEMON', 'BREATHE_ACID'),
    ('DEMON', 'BREATHE_LIGHTNING'),
    ('DEMON', 'ROAR'),
    ('DRAGON_FIRE', 'BREATHE_FIRE'),
    ('DRAGON_FIRE', 'SWEEP'),
    ('DRAGON_FIRE', 'ROAR'),
    ('DRAGON_FROST', 'BREATHE_FROST'),
    ('DRAGON_FROST', 'SWEEP'),
    ('DRAGON_FROST', 'ROAR'),
    ('DRAGON_ACID', 'BREATHE_ACID'),
    ('DRAGON_ACID', 'SWEEP'),
    ('DRAGON_ACID', 'ROAR'),
    ('DRAGON_GAS', 'BREATHE_GAS'),
    ('DRAGON_GAS', 'SWEEP'),
    ('DRAGON_GAS', 'ROAR'),
    ('DRAGON_LIGHTNING', 'BREATHE_LIGHTNING'),
    ('DRAGON_LIGHTNING', 'SWEEP'),
    ('DRAGON_LIGHTNING', 'ROAR')
) AS v(race, ability_name)
JOIN "Ability" a ON a.plain_name = v.ability_name
ON CONFLICT (race, ability_id) DO NOTHING;

WITH race_rule(race, ability_name, priority, chance_pct, cooldown_s, conditions, target) AS (VALUES
    ('DRAGON_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_FIRE', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGON_FIRE', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGON_FROST', 'BREATHE_FROST', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_FROST', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGON_FROST', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGON_ACID', 'BREATHE_ACID', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_ACID', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGON_ACID', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGON_GAS', 'BREATHE_GAS', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_GAS', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGON_GAS', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGON_LIGHTNING', 'BREATHE_LIGHTNING', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_LIGHTNING', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGON_LIGHTNING', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGONBORN_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGONBORN_FIRE', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGONBORN_FIRE', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGONBORN_FROST', 'BREATHE_FROST', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGONBORN_FROST', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGONBORN_FROST', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGONBORN_ACID', 'BREATHE_ACID', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGONBORN_ACID', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGONBORN_ACID', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGONBORN_GAS', 'BREATHE_GAS', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGONBORN_GAS', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGONBORN_GAS', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGONBORN_LIGHTNING', 'BREATHE_LIGHTNING', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGONBORN_LIGHTNING', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGONBORN_LIGHTNING', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_FIRE', 10, 100, 0, '{"composition": ["FIRE", "LAVA"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_GAS', 11, 100, 0, '{"composition": ["METAL", "BONE", "PLANT"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_FROST', 12, 100, 0, '{"composition": ["WATER", "ICE", "MIST"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_ACID', 13, 100, 0, '{"composition": ["EARTH", "STONE"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_LIGHTNING', 14, 100, 0, '{"composition": ["AIR", "ETHER"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_FIRE', 20, 100, 0, '{"in_combat": true, "level_roll": {"max": 1, "min": 0}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_GAS', 21, 100, 0, '{"in_combat": true, "level_roll": {"max": 2, "min": 1}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_FROST', 22, 100, 0, '{"in_combat": true, "level_roll": {"max": 3, "min": 2}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_ACID', 23, 100, 0, '{"in_combat": true, "level_roll": {"max": 4, "min": 3}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DRAGON_GENERAL', 'BREATHE_LIGHTNING', 24, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 4}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DRAGON_GENERAL', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto'),
    ('DRAGON_GENERAL', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto'),
    ('DEMON', 'BREATHE_FIRE', 10, 100, 0, '{"composition": ["FIRE", "LAVA"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DEMON', 'BREATHE_GAS', 11, 100, 0, '{"composition": ["METAL", "BONE", "PLANT"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DEMON', 'BREATHE_FROST', 12, 100, 0, '{"composition": ["WATER", "ICE", "MIST"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DEMON', 'BREATHE_ACID', 13, 100, 0, '{"composition": ["EARTH", "STONE"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DEMON', 'BREATHE_LIGHTNING', 14, 100, 0, '{"composition": ["AIR", "ETHER"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto'),
    ('DEMON', 'BREATHE_FIRE', 20, 100, 0, '{"in_combat": true, "level_roll": {"max": 1, "min": 0}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DEMON', 'BREATHE_GAS', 21, 100, 0, '{"in_combat": true, "level_roll": {"max": 2, "min": 1}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DEMON', 'BREATHE_FROST', 22, 100, 0, '{"in_combat": true, "level_roll": {"max": 3, "min": 2}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DEMON', 'BREATHE_ACID', 23, 100, 0, '{"in_combat": true, "level_roll": {"max": 4, "min": 3}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DEMON', 'BREATHE_LIGHTNING', 24, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 4}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto'),
    ('DEMON', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto')
)
INSERT INTO "RaceAiRules" (race, ability_id, priority, chance_pct, cooldown_s, conditions, target, enabled)
SELECT rr.race::"Race", a.id, rr.priority::int, rr.chance_pct::int, rr.cooldown_s::int,
       rr.conditions::jsonb, rr.target, true
FROM race_rule rr
JOIN "Ability" a ON a.plain_name = rr.ability_name
JOIN "RaceAbilities" ra ON ra.race = rr.race::"Race" AND ra.ability_id = a.id
ON CONFLICT (race, ability_id, priority) DO UPDATE SET
    chance_pct = EXCLUDED.chance_pct, cooldown_s = EXCLUDED.cooldown_s,
    conditions = EXCLUDED.conditions, target = EXCLUDED.target
WHERE ("RaceAiRules".chance_pct, "RaceAiRules".cooldown_s, "RaceAiRules".conditions,
       "RaceAiRules".target)
      IS DISTINCT FROM (EXCLUDED.chance_pct, EXCLUDED.cooldown_s, EXCLUDED.conditions,
                        EXCLUDED.target);

COMMIT;
