-- Topic help articles (generated by help_seeder.render_sql(insert_only=True)).
-- Source: fierylib/data/help/{combat,death,stealth,tank,touchstone}.md. Do not edit
-- by hand; edit the markdown and regenerate (tests/test_topic_help_sql.py checks).
--
-- fierymud-rs used to hard-code these articles (TOPIC_HELP_ARTICLES in commands/info.rs)
-- as a fallback behind the HelpEntry table. Insert-only and idempotent: an article is
-- added only when no entry readable by every player (min_level <= 0) already carries
-- its primary keyword, so existing legacy or builder-edited entries are never touched
-- and a re-run changes 0 rows. (`fierylib seed help` overwrites by primary keyword
-- instead; use it on a fresh database.)

-- combat: Combat
INSERT INTO "HelpEntry"
  (keywords, title, content, min_level, category, usage, source_file, updated_at)
SELECT
  ARRAY['combat']::text[],
  'Combat',
  $help$Combat uses an accuracy-vs-evasion d100 contest.

Hit chance = 50 + (attacker.accuracy - defender.evasion) / 2,
clamped to [1, 99]. Each point of Acc or Eva on your score sheet
shifts hit chance by 0.5%. Atk is a percent multiplier on weapon damage:
Atk=+50 means swings deal +50% damage.

Posture matters — sitting, resting, kneeling, or sleeping subtracts from
your evasion (Sleeping = -30, full reset).

A swing every 4 seconds per side; 'kill X' fires one immediate
opening swing then continues on cadence. 'consider {target}' shows your
predicted hit rates and the target's current HP.

Class tools: warriors taunt and bash; rogues hide then
backstab for a +50% opener; clerics heal allies; mages cast for fire/ice/
lightning damage.$help$,
  0,
  'guide',
  NULL,
  'data/help/combat.md',
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM "HelpEntry" h, unnest(h.keywords) k
  WHERE h.min_level <= 0 AND lower(k) = 'combat'
);

-- death: Death
INSERT INTO "HelpEntry"
  (keywords, title, content, min_level, category, usage, source_file, updated_at)
SELECT
  ARRAY['death']::text[],
  'Death',
  $help$When you die, your spirit lingers where you fell while your corpse drops
at the death scene. Type release to return to your recall point
at full HP.

Release precedence:
1. Last touchstone you 'touch'ed
2. Your race's home room (where character creation spawns)
3. The Void (last resort)

Corpse decay: a player's corpse keeps for several days, so
take your time — log off, sleep on it, come back. Mob corpses decay in
10 minutes. You'll lose some XP on death (the standard fierymud-tier
penalty); items stay on the corpse for you to retrieve.$help$,
  0,
  'guide',
  NULL,
  'data/help/death.md',
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM "HelpEntry" h, unnest(h.keywords) k
  WHERE h.min_level <= 0 AND lower(k) = 'death'
);

-- stealth: Stealth
INSERT INTO "HelpEntry"
  (keywords, title, content, min_level, category, usage, source_file, updated_at)
SELECT
  ARRAY['stealth']::text[],
  'Stealth',
  $help$hide rolls how well you hide from your hide skill, Dexterity and
Intelligence. Anyone whose perception is below that number cannot see
you; your group always can. Anything but looking around, hiding, moving
and the like gives you away, and walking wears it down (sneak
slows that). search can find a hider; point gives one
away.

While hidden, your next swing lands an opening-strike bonus:
+acc, +50% damage, softened by the defender's Perception.
It is gone after that first swing regardless of outcome.

backstab is the rogue's specialty stealth strike: pierce-weapon
only, big multiplier on the weapon roll, even bigger when paired with
hide first. visible drops your hiding without swinging.$help$,
  0,
  'guide',
  NULL,
  'data/help/stealth.md',
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM "HelpEntry" h, unnest(h.keywords) k
  WHERE h.min_level <= 0 AND lower(k) = 'stealth'
);

-- tank: Tank
INSERT INTO "HelpEntry"
  (keywords, title, content, min_level, category, usage, source_file, updated_at)
SELECT
  ARRAY['tank', 'tanking']::text[],
  'Tank',
  $help$The tank role pulls a mob's attention so the healer can keep them alive
while the DPS burns the mob down.

taunt [target] forces the target to focus on you,
regardless of who they were previously engaging. You're also pushed to
the front of the target's grudge list, so when the current victim falls
the target re-engages you first.

rescue [ally] swaps the target's attention to you for one
pull (less reliable than taunt but doesn't require facing the mob).
guard [ally] intercepts swings aimed at the protected
ally — they hit you instead.$help$,
  0,
  'guide',
  NULL,
  'data/help/tank.md',
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM "HelpEntry" h, unnest(h.keywords) k
  WHERE h.min_level <= 0 AND lower(k) = 'tank'
);

-- touchstone: Recall and Touchstones
INSERT INTO "HelpEntry"
  (keywords, title, content, min_level, category, usage, source_file, updated_at)
SELECT
  ARRAY['touchstone']::text[],
  'Recall and Touchstones',
  $help$recall teleports you to your bound touchstone. Bind a new one
by walking to a recall stone and typing touch. Most major town
halls and temples carry a stone.

If you've never touched a stone, 'recall' will nudge you toward one.
Newbies start with the Mielikki temple bound by default. Some rooms
have NoRecallRoom set — recall refuses to teleport out of those
(dungeons, quest cells).$help$,
  0,
  'guide',
  NULL,
  'data/help/touchstone.md',
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM "HelpEntry" h, unnest(h.keywords) k
  WHERE h.min_level <= 0 AND lower(k) = 'touchstone'
);
