-- Object flag effects, part 2: bits left unmapped by 2026-10-08-object-flag-effects.sql,
-- plus the ObjectResistance backfill dev/prod never got.
--
-- 1. status flags: legacy PROTECT_EVIL -> protect_evil, PROTECT_GOOD -> protect_good,
--    TONGUES -> language_fluency, FAMILIARITY -> familiarity (OBJECT_EFFECT_FLAG_TO_STATUS_FLAG in
--    src/fierylib/converters/flag_normalizer.py). Objects with a `status` ObjectEffects row get the
--    missing flags appended to modifier_data.flags (existing flags, order and other keys are kept);
--    objects without one get a new row. Re-running adds nothing.
-- 2. worn globe: MINOR_GLOBE / MAJOR_GLOBE -> one `globe` Effect row, strength = max absorbed
--    circle (3 / 6), inserted only if the object has no `globe` row (fierymud-rs MaxAbsorbCircle).
-- 3. ObjectResistance: PROTECT_FIRE/COLD/AIR(shock)/EARTH(acid), FIRESHIELD, COLDSHIELD, NEGATE_*,
--    STONE_SKIN (physical 25) via the importer's EFFECT_TO_RESISTANCE; inserted only where the
--    (object, element) pair has no row (unique key), so existing/builder values are untouched.
-- Not mapped on worn gear: CHARM, TAMED, ON_FIRE, HURT_THROAT (nonsensical state on equipment),
-- VITALITY, GLORY, NO_TRACK (no runtime marker or flag).
-- Objects missing from "Objects" are skipped by the join. Data only, no DDL.
-- Generated by scripts/gen_object_flag_effects2_sql.py from lib/world/obj/*.obj
-- (id = object vnum - zone*100). 48 status, 15 globe, 55 resistance rows.
-- Flag usage (objects): familiarity=6, globe_major=5, globe_minor=10, language_fluency=9, protect_evil=25, protect_good=21, resist_COLD=1, resist_FIRE=42, resist_PHYSICAL=12

BEGIN;

-- 1a. New `status` rows for objects that have none.
INSERT INTO "ObjectEffects" (object_zone_id, object_id, effect_id, strength, modifier_data)
SELECT v.zone_id, v.object_id, e.id, 1, v.flags::jsonb
FROM (VALUES
    (2, 145, '{"flags": ["protect_evil"]}'),
    (2, 146, '{"flags": ["protect_evil"]}'),
    (2, 147, '{"flags": ["protect_evil"]}'),
    (2, 148, '{"flags": ["protect_evil"]}'),
    (2, 149, '{"flags": ["protect_evil"]}'),
    (4, 2, '{"flags": ["protect_evil", "protect_good"]}'),
    (4, 11, '{"flags": ["familiarity"]}'),
    (4, 12, '{"flags": ["protect_evil"]}'),
    (4, 22, '{"flags": ["protect_evil", "protect_good"]}'),
    (4, 24, '{"flags": ["language_fluency"]}'),
    (4, 31, '{"flags": ["protect_evil"]}'),
    (4, 52, '{"flags": ["protect_good"]}'),
    (4, 65, '{"flags": ["protect_evil", "protect_good"]}'),
    (4, 89, '{"flags": ["familiarity", "protect_evil", "protect_good"]}'),
    (4, 117, '{"flags": ["language_fluency", "protect_evil"]}'),
    (4, 126, '{"flags": ["protect_good"]}'),
    (4, 137, '{"flags": ["protect_evil"]}'),
    (4, 139, '{"flags": ["protect_evil"]}'),
    (12, 70, '{"flags": ["protect_good"]}'),
    (12, 95, '{"flags": ["protect_good"]}'),
    (40, 7, '{"flags": ["language_fluency"]}'),
    (64, 23, '{"flags": ["language_fluency", "protect_good"]}'),
    (117, 111, '{"flags": ["protect_evil", "protect_good"]}'),
    (123, 107, '{"flags": ["language_fluency"]}'),
    (123, 108, '{"flags": ["language_fluency"]}'),
    (123, 110, '{"flags": ["protect_evil", "protect_good"]}'),
    (123, 112, '{"flags": ["familiarity"]}'),
    (123, 150, '{"flags": ["protect_evil", "protect_good"]}'),
    (123, 158, '{"flags": ["protect_good"]}'),
    (188, 75, '{"flags": ["familiarity"]}'),
    (237, 4, '{"flags": ["protect_good"]}'),
    (238, 95, '{"flags": ["protect_good"]}'),
    (370, 16, '{"flags": ["protect_good"]}'),
    (470, 2, '{"flags": ["language_fluency"]}'),
    (481, 151, '{"flags": ["protect_good"]}'),
    (484, 16, '{"flags": ["protect_evil"]}'),
    (489, 4, '{"flags": ["protect_good"]}'),
    (489, 8, '{"flags": ["language_fluency", "protect_evil", "protect_good"]}'),
    (489, 21, '{"flags": ["protect_evil", "protect_good"]}'),
    (500, 10, '{"flags": ["protect_evil"]}'),
    (520, 10, '{"flags": ["protect_evil"]}'),
    (534, 100, '{"flags": ["protect_evil"]}'),
    (554, 98, '{"flags": ["protect_good"]}'),
    (555, 5, '{"flags": ["protect_evil"]}'),
    (557, 90, '{"flags": ["familiarity"]}'),
    (590, 12, '{"flags": ["language_fluency"]}'),
    (625, 9, '{"flags": ["protect_evil"]}'),
    (625, 52, '{"flags": ["familiarity"]}')
) AS v(zone_id, object_id, flags)
JOIN "Effect" e ON e.name = 'status'
JOIN "Objects" o ON o.zone_id = v.zone_id AND o.id = v.object_id
WHERE NOT EXISTS (
    SELECT 1 FROM "ObjectEffects" oe
    WHERE oe.object_zone_id = v.zone_id AND oe.object_id = v.object_id AND oe.effect_id = e.id
);

-- 1b. Append the missing flags to an existing `status` row (the lowest id when there are several).
WITH v(zone_id, object_id, flags) AS (VALUES
    (2, 145, '{"flags": ["protect_evil"]}'),
    (2, 146, '{"flags": ["protect_evil"]}'),
    (2, 147, '{"flags": ["protect_evil"]}'),
    (2, 148, '{"flags": ["protect_evil"]}'),
    (2, 149, '{"flags": ["protect_evil"]}'),
    (4, 2, '{"flags": ["protect_evil", "protect_good"]}'),
    (4, 11, '{"flags": ["familiarity"]}'),
    (4, 12, '{"flags": ["protect_evil"]}'),
    (4, 22, '{"flags": ["protect_evil", "protect_good"]}'),
    (4, 24, '{"flags": ["language_fluency"]}'),
    (4, 31, '{"flags": ["protect_evil"]}'),
    (4, 52, '{"flags": ["protect_good"]}'),
    (4, 65, '{"flags": ["protect_evil", "protect_good"]}'),
    (4, 89, '{"flags": ["familiarity", "protect_evil", "protect_good"]}'),
    (4, 117, '{"flags": ["language_fluency", "protect_evil"]}'),
    (4, 126, '{"flags": ["protect_good"]}'),
    (4, 137, '{"flags": ["protect_evil"]}'),
    (4, 139, '{"flags": ["protect_evil"]}'),
    (12, 70, '{"flags": ["protect_good"]}'),
    (12, 95, '{"flags": ["protect_good"]}'),
    (40, 7, '{"flags": ["language_fluency"]}'),
    (64, 23, '{"flags": ["language_fluency", "protect_good"]}'),
    (117, 111, '{"flags": ["protect_evil", "protect_good"]}'),
    (123, 107, '{"flags": ["language_fluency"]}'),
    (123, 108, '{"flags": ["language_fluency"]}'),
    (123, 110, '{"flags": ["protect_evil", "protect_good"]}'),
    (123, 112, '{"flags": ["familiarity"]}'),
    (123, 150, '{"flags": ["protect_evil", "protect_good"]}'),
    (123, 158, '{"flags": ["protect_good"]}'),
    (188, 75, '{"flags": ["familiarity"]}'),
    (237, 4, '{"flags": ["protect_good"]}'),
    (238, 95, '{"flags": ["protect_good"]}'),
    (370, 16, '{"flags": ["protect_good"]}'),
    (470, 2, '{"flags": ["language_fluency"]}'),
    (481, 151, '{"flags": ["protect_good"]}'),
    (484, 16, '{"flags": ["protect_evil"]}'),
    (489, 4, '{"flags": ["protect_good"]}'),
    (489, 8, '{"flags": ["language_fluency", "protect_evil", "protect_good"]}'),
    (489, 21, '{"flags": ["protect_evil", "protect_good"]}'),
    (500, 10, '{"flags": ["protect_evil"]}'),
    (520, 10, '{"flags": ["protect_evil"]}'),
    (534, 100, '{"flags": ["protect_evil"]}'),
    (554, 98, '{"flags": ["protect_good"]}'),
    (555, 5, '{"flags": ["protect_evil"]}'),
    (557, 90, '{"flags": ["familiarity"]}'),
    (590, 12, '{"flags": ["language_fluency"]}'),
    (625, 9, '{"flags": ["protect_evil"]}'),
    (625, 52, '{"flags": ["familiarity"]}')
), todo AS (
    SELECT oe.id,
           oe.modifier_data,
           COALESCE(oe.modifier_data -> 'flags', '[]'::jsonb) AS old_flags,
           (SELECT COALESCE(jsonb_agg(f ORDER BY f), '[]'::jsonb)
              FROM jsonb_array_elements_text(v.flags::jsonb -> 'flags') f
             WHERE NOT (COALESCE(oe.modifier_data -> 'flags', '[]'::jsonb) @> to_jsonb(f))) AS add_flags
    FROM v
    JOIN "Effect" e ON e.name = 'status'
    JOIN "ObjectEffects" oe ON oe.object_zone_id = v.zone_id AND oe.object_id = v.object_id AND oe.effect_id = e.id
    WHERE oe.id = (SELECT MIN(x.id) FROM "ObjectEffects" x
                   WHERE x.object_zone_id = v.zone_id AND x.object_id = v.object_id AND x.effect_id = e.id)
      AND jsonb_typeof(COALESCE(oe.modifier_data -> 'flags', '[]'::jsonb)) = 'array'
)
UPDATE "ObjectEffects" oe
SET modifier_data = jsonb_set(todo.modifier_data, '{flags}', todo.old_flags || todo.add_flags)
FROM todo
WHERE oe.id = todo.id AND todo.add_flags <> '[]'::jsonb;

-- 2. Worn globe (strength = max absorbed circle), only where the object has no `globe` row.
INSERT INTO "ObjectEffects" (object_zone_id, object_id, effect_id, strength, modifier_data)
SELECT v.zone_id, v.object_id, e.id, v.circle, '{}'::jsonb
FROM (VALUES
    (4, 88, 6),
    (10, 47, 6),
    (23, 34, 3),
    (23, 39, 3),
    (23, 40, 3),
    (43, 19, 3),
    (80, 50, 3),
    (123, 134, 3),
    (237, 63, 3),
    (238, 6, 6),
    (481, 10, 3),
    (530, 0, 3),
    (533, 8, 6),
    (557, 59, 6),
    (557, 61, 3)
) AS v(zone_id, object_id, circle)
JOIN "Effect" e ON e.name = 'globe'
JOIN "Objects" o ON o.zone_id = v.zone_id AND o.id = v.object_id
WHERE NOT EXISTS (
    SELECT 1 FROM "ObjectEffects" oe
    WHERE oe.object_zone_id = v.zone_id AND oe.object_id = v.object_id AND oe.effect_id = e.id
);

-- 3. ObjectResistance backfill (importer EFFECT_TO_RESISTANCE; strongest value per element).
INSERT INTO "ObjectResistance" (object_zone_id, object_id, element, value, allow_absorption)
SELECT v.zone_id, v.object_id, v.element::"ElementType", v.value, false
FROM (VALUES
    (2, 141, 'FIRE', 25),
    (2, 142, 'FIRE', 25),
    (2, 143, 'FIRE', 25),
    (2, 144, 'FIRE', 25),
    (2, 145, 'FIRE', 25),
    (2, 146, 'FIRE', 25),
    (2, 147, 'FIRE', 25),
    (2, 148, 'FIRE', 25),
    (2, 149, 'FIRE', 25),
    (2, 189, 'COLD', 25),
    (4, 1, 'FIRE', 25),
    (4, 10, 'FIRE', 25),
    (4, 65, 'FIRE', 25),
    (4, 78, 'FIRE', 25),
    (4, 79, 'FIRE', 25),
    (4, 138, 'FIRE', 25),
    (4, 139, 'FIRE', 25),
    (4, 144, 'FIRE', 25),
    (4, 156, 'FIRE', 25),
    (4, 157, 'FIRE', 25),
    (4, 162, 'PHYSICAL', 25),
    (4, 164, 'FIRE', 25),
    (4, 165, 'PHYSICAL', 25),
    (4, 166, 'PHYSICAL', 25),
    (4, 176, 'FIRE', 25),
    (4, 177, 'FIRE', 25),
    (4, 185, 'FIRE', 25),
    (4, 186, 'FIRE', 25),
    (4, 189, 'PHYSICAL', 25),
    (4, 199, 'FIRE', 25),
    (12, 5, 'PHYSICAL', 25),
    (52, 10, 'FIRE', 25),
    (63, 8, 'FIRE', 25),
    (103, 15, 'PHYSICAL', 25),
    (123, 99, 'FIRE', 25),
    (123, 101, 'FIRE', 25),
    (123, 104, 'FIRE', 25),
    (123, 105, 'FIRE', 25),
    (123, 111, 'PHYSICAL', 25),
    (123, 115, 'FIRE', 25),
    (123, 116, 'PHYSICAL', 25),
    (123, 122, 'PHYSICAL', 25),
    (123, 123, 'PHYSICAL', 25),
    (123, 124, 'PHYSICAL', 25),
    (123, 125, 'FIRE', 25),
    (123, 138, 'FIRE', 25),
    (123, 151, 'FIRE', 25),
    (123, 155, 'FIRE', 25),
    (123, 157, 'FIRE', 25),
    (123, 198, 'FIRE', 25),
    (123, 199, 'FIRE', 25),
    (237, 80, 'FIRE', 25),
    (300, 101, 'PHYSICAL', 25),
    (489, 22, 'FIRE', 25),
    (625, 52, 'FIRE', 25)
) AS v(zone_id, object_id, element, value)
JOIN "Objects" o ON o.zone_id = v.zone_id AND o.id = v.object_id
WHERE NOT EXISTS (
    SELECT 1 FROM "ObjectResistance" r
    WHERE r.object_zone_id = v.zone_id AND r.object_id = v.object_id AND r.element = v.element::"ElementType"
);

COMMIT;
