-- Mob AI: race rules (dragon / demon breath, sweep, roar), WP-D of ops/plans/mob-ai.md.
--
-- Legacy dragonlike_attack (mobact.cpp): roll = rand(0, 150 - level); breath if roll < 5, sweep if
-- roll < 10, roar if roll < 15, for the DRAGON_* / DRAGONBORN_* races and DEMON. The element comes
-- from the body composition (earth/stone acid, air/ether lightning, fire/lava fire, water/ice/mist
-- frost, metal/bone/plant gas), any other composition rolls it. The rules express the bands with the
-- level_roll condition (one shared roll per mob per round) and the element with composition /
-- not_composition. min_level keeps a low-level demon from breathing, sweeping or roaring.
--
--   1. creates "RaceAiRules" or adds its min_level / seed_key / seed_hash columns (matches muditor
--      packages/db/prisma/schema.prisma, db push compatible),
--   2. adds the RaceAbilities rows the races lack (legacy races.cpp assign_race_skills): the DRAGON_*
--      races and DEMON had no BREATHE_* / SWEEP / ROAR row; DRAGONBORN_* already have their breath,
--   3. seeds the rules.
-- Generated by `python -m fierylib.seeders.mob_ai_seeder --write-sql` from data/mob_ai_seed.json; a
-- unit test keeps the two in sync. Standalone (own table); the server loads it at every boot but uses
-- it only with mob_ai.enabled on. Keyed by Races.race (enum) and Ability.plain_name, never numeric ids.
--
-- Ownership: each rule has a stable seed_key and a seed_hash of the values it last wrote. Step 3
-- (a) claims existing un-keyed rows that still match the seed, (b) upserts on seed_key, updating a
-- row only while its stored hash equals the hash of its current values, so a builder-edited row
-- (hash cleared or stale) is left alone, and (c) disables seed-owned rows whose key left the seed.
-- A second run changes 0 rows.

BEGIN;

CREATE TABLE IF NOT EXISTS "RaceAiRules" (
    "id" SERIAL NOT NULL,
    "race" "Race" NOT NULL,
    "ability_id" INTEGER NOT NULL,
    "priority" INTEGER NOT NULL,
    "chance_pct" INTEGER NOT NULL DEFAULT 100,
    "cooldown_s" INTEGER NOT NULL DEFAULT 0,
    "conditions" JSONB,
    "target" TEXT NOT NULL,
    "min_level" INTEGER,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "seed_key" TEXT,
    "seed_hash" TEXT,

    CONSTRAINT "RaceAiRules_pkey" PRIMARY KEY ("id")
);

-- A table created by an earlier version of this patch lacks the newer columns.
ALTER TABLE "RaceAiRules"
    ADD COLUMN IF NOT EXISTS "min_level" INTEGER,
    ADD COLUMN IF NOT EXISTS "seed_key" TEXT,
    ADD COLUMN IF NOT EXISTS "seed_hash" TEXT;

CREATE INDEX IF NOT EXISTS "RaceAiRules_race_idx" ON "RaceAiRules"("race");

CREATE UNIQUE INDEX IF NOT EXISTS "RaceAiRules_race_ability_id_priority_key"
    ON "RaceAiRules"("race", "ability_id", "priority");

CREATE UNIQUE INDEX IF NOT EXISTS "RaceAiRules_seed_key_key" ON "RaceAiRules"("seed_key");

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'RaceAiRules_race_fkey') THEN
        ALTER TABLE "RaceAiRules" ADD CONSTRAINT "RaceAiRules_race_fkey"
            FOREIGN KEY ("race") REFERENCES "Races"("race") ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'RaceAiRules_ability_id_fkey') THEN
        ALTER TABLE "RaceAiRules" ADD CONSTRAINT "RaceAiRules_ability_id_fkey"
            FOREIGN KEY ("ability_id") REFERENCES "Ability"("id") ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
END
$$;

INSERT INTO "RaceAbilities" (race, ability_id, category, bonus, proficiency_cap)
SELECT v.race::"Race", a.id, 'PRIMARY', 0, 100
FROM (VALUES
    ('DRAGON_GENERAL', 'BREATHE_FIRE'),
    ('DRAGON_GENERAL', 'BREATHE_GAS'),
    ('DRAGON_GENERAL', 'BREATHE_FROST'),
    ('DRAGON_GENERAL', 'BREATHE_ACID'),
    ('DRAGON_GENERAL', 'BREATHE_LIGHTNING'),
    ('DRAGON_GENERAL', 'SWEEP'),
    ('DRAGON_GENERAL', 'ROAR'),
    ('DEMON', 'BREATHE_FIRE'),
    ('DEMON', 'BREATHE_GAS'),
    ('DEMON', 'BREATHE_FROST'),
    ('DEMON', 'BREATHE_ACID'),
    ('DEMON', 'BREATHE_LIGHTNING'),
    ('DEMON', 'ROAR'),
    ('DRAGON_FIRE', 'BREATHE_FIRE'),
    ('DRAGON_FIRE', 'SWEEP'),
    ('DRAGON_FIRE', 'ROAR'),
    ('DRAGON_FROST', 'BREATHE_FROST'),
    ('DRAGON_FROST', 'SWEEP'),
    ('DRAGON_FROST', 'ROAR'),
    ('DRAGON_ACID', 'BREATHE_ACID'),
    ('DRAGON_ACID', 'SWEEP'),
    ('DRAGON_ACID', 'ROAR'),
    ('DRAGON_GAS', 'BREATHE_GAS'),
    ('DRAGON_GAS', 'SWEEP'),
    ('DRAGON_GAS', 'ROAR'),
    ('DRAGON_LIGHTNING', 'BREATHE_LIGHTNING'),
    ('DRAGON_LIGHTNING', 'SWEEP'),
    ('DRAGON_LIGHTNING', 'ROAR')
) AS v(race, ability_name)
JOIN "Ability" a ON a.plain_name = v.ability_name
ON CONFLICT (race, ability_id) DO NOTHING;

WITH race_rule(race, rule_key, ability_name, priority, chance_pct, cooldown_s, conditions, target, min_level) AS (VALUES
    ('DRAGON_FIRE', 'DRAGON_FIRE:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_FIRE', 'DRAGON_FIRE:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_FIRE', 'DRAGON_FIRE:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_FROST', 'DRAGON_FROST:BREATHE_FROST', 'BREATHE_FROST', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_FROST', 'DRAGON_FROST:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_FROST', 'DRAGON_FROST:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_ACID', 'DRAGON_ACID:BREATHE_ACID', 'BREATHE_ACID', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_ACID', 'DRAGON_ACID:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_ACID', 'DRAGON_ACID:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_GAS', 'DRAGON_GAS:BREATHE_GAS', 'BREATHE_GAS', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GAS', 'DRAGON_GAS:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_GAS', 'DRAGON_GAS:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:BREATHE_FROST', 'BREATHE_FROST', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:BREATHE_ACID', 'BREATHE_ACID', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:BREATHE_GAS', 'BREATHE_GAS', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"composition": ["FIRE", "LAVA"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_GAS', 'BREATHE_GAS', 11, 100, 0, '{"composition": ["METAL", "BONE", "PLANT"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FROST', 'BREATHE_FROST', 12, 100, 0, '{"composition": ["WATER", "ICE", "MIST"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_ACID', 'BREATHE_ACID', 13, 100, 0, '{"composition": ["EARTH", "STONE"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 14, 100, 0, '{"composition": ["AIR", "ETHER"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FIRE:other', 'BREATHE_FIRE', 20, 100, 0, '{"in_combat": true, "level_roll": {"max": 1, "min": 0}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_GAS:other', 'BREATHE_GAS', 21, 100, 0, '{"in_combat": true, "level_roll": {"max": 2, "min": 1}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FROST:other', 'BREATHE_FROST', 22, 100, 0, '{"in_combat": true, "level_roll": {"max": 3, "min": 2}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_ACID:other', 'BREATHE_ACID', 23, 100, 0, '{"in_combat": true, "level_roll": {"max": 4, "min": 3}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_LIGHTNING:other', 'BREATHE_LIGHTNING', 24, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 4}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DEMON', 'DEMON:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"composition": ["FIRE", "LAVA"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_GAS', 'BREATHE_GAS', 11, 100, 0, '{"composition": ["METAL", "BONE", "PLANT"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FROST', 'BREATHE_FROST', 12, 100, 0, '{"composition": ["WATER", "ICE", "MIST"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_ACID', 'BREATHE_ACID', 13, 100, 0, '{"composition": ["EARTH", "STONE"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 14, 100, 0, '{"composition": ["AIR", "ETHER"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FIRE:other', 'BREATHE_FIRE', 20, 100, 0, '{"in_combat": true, "level_roll": {"max": 1, "min": 0}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_GAS:other', 'BREATHE_GAS', 21, 100, 0, '{"in_combat": true, "level_roll": {"max": 2, "min": 1}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FROST:other', 'BREATHE_FROST', 22, 100, 0, '{"in_combat": true, "level_roll": {"max": 3, "min": 2}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_ACID:other', 'BREATHE_ACID', 23, 100, 0, '{"in_combat": true, "level_roll": {"max": 4, "min": 3}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_LIGHTNING:other', 'BREATHE_LIGHTNING', 24, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 4}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25)
), raw AS (
    SELECT rr.race::"Race" AS race, rr.rule_key AS seed_key, a.id AS ability_id, rr.priority::int AS priority,
           rr.chance_pct::int AS chance_pct, rr.cooldown_s::int AS cooldown_s,
           rr.conditions::jsonb AS conditions, rr.target AS target, rr.min_level::int AS min_level
    FROM race_rule rr
    JOIN "Ability" a ON a.plain_name = rr.ability_name
    JOIN "RaceAbilities" ra ON ra.race = rr.race::"Race" AND ra.ability_id = a.id
), seed AS (
    SELECT raw.*, md5(concat_ws('|', raw.ability_id, raw.priority, raw.chance_pct, raw.cooldown_s, coalesce(raw.conditions::text, ''), raw.target, coalesce(raw.min_level::text, ''))) AS seed_hash FROM raw
)
UPDATE "RaceAiRules" r SET seed_key = s.seed_key, seed_hash = md5(concat_ws('|', r.ability_id, r.priority, r.chance_pct, r.cooldown_s, coalesce(r.conditions::text, ''), r.target, coalesce(r.min_level::text, '')))
FROM seed s
WHERE r.seed_key IS NULL AND r.race = s.race AND r.ability_id = s.ability_id
  AND r.priority = s.priority AND r.chance_pct = s.chance_pct
  AND r.conditions IS NOT DISTINCT FROM s.conditions AND r.target = s.target
  AND (r.cooldown_s = s.cooldown_s OR r.cooldown_s = 0)
  AND (r.min_level IS NOT DISTINCT FROM s.min_level OR r.min_level IS NULL)
  AND NOT EXISTS (SELECT 1 FROM "RaceAiRules" k WHERE k.seed_key = s.seed_key);

WITH race_rule(race, rule_key, ability_name, priority, chance_pct, cooldown_s, conditions, target, min_level) AS (VALUES
    ('DRAGON_FIRE', 'DRAGON_FIRE:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_FIRE', 'DRAGON_FIRE:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_FIRE', 'DRAGON_FIRE:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_FROST', 'DRAGON_FROST:BREATHE_FROST', 'BREATHE_FROST', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_FROST', 'DRAGON_FROST:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_FROST', 'DRAGON_FROST:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_ACID', 'DRAGON_ACID:BREATHE_ACID', 'BREATHE_ACID', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_ACID', 'DRAGON_ACID:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_ACID', 'DRAGON_ACID:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_GAS', 'DRAGON_GAS:BREATHE_GAS', 'BREATHE_GAS', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GAS', 'DRAGON_GAS:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_GAS', 'DRAGON_GAS:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:BREATHE_FROST', 'BREATHE_FROST', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:BREATHE_ACID', 'BREATHE_ACID', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:BREATHE_GAS', 'BREATHE_GAS', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"composition": ["FIRE", "LAVA"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_GAS', 'BREATHE_GAS', 11, 100, 0, '{"composition": ["METAL", "BONE", "PLANT"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FROST', 'BREATHE_FROST', 12, 100, 0, '{"composition": ["WATER", "ICE", "MIST"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_ACID', 'BREATHE_ACID', 13, 100, 0, '{"composition": ["EARTH", "STONE"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 14, 100, 0, '{"composition": ["AIR", "ETHER"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FIRE:other', 'BREATHE_FIRE', 20, 100, 0, '{"in_combat": true, "level_roll": {"max": 1, "min": 0}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_GAS:other', 'BREATHE_GAS', 21, 100, 0, '{"in_combat": true, "level_roll": {"max": 2, "min": 1}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FROST:other', 'BREATHE_FROST', 22, 100, 0, '{"in_combat": true, "level_roll": {"max": 3, "min": 2}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_ACID:other', 'BREATHE_ACID', 23, 100, 0, '{"in_combat": true, "level_roll": {"max": 4, "min": 3}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_LIGHTNING:other', 'BREATHE_LIGHTNING', 24, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 4}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DEMON', 'DEMON:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"composition": ["FIRE", "LAVA"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_GAS', 'BREATHE_GAS', 11, 100, 0, '{"composition": ["METAL", "BONE", "PLANT"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FROST', 'BREATHE_FROST', 12, 100, 0, '{"composition": ["WATER", "ICE", "MIST"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_ACID', 'BREATHE_ACID', 13, 100, 0, '{"composition": ["EARTH", "STONE"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 14, 100, 0, '{"composition": ["AIR", "ETHER"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FIRE:other', 'BREATHE_FIRE', 20, 100, 0, '{"in_combat": true, "level_roll": {"max": 1, "min": 0}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_GAS:other', 'BREATHE_GAS', 21, 100, 0, '{"in_combat": true, "level_roll": {"max": 2, "min": 1}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FROST:other', 'BREATHE_FROST', 22, 100, 0, '{"in_combat": true, "level_roll": {"max": 3, "min": 2}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_ACID:other', 'BREATHE_ACID', 23, 100, 0, '{"in_combat": true, "level_roll": {"max": 4, "min": 3}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_LIGHTNING:other', 'BREATHE_LIGHTNING', 24, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 4}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25)
), raw AS (
    SELECT rr.race::"Race" AS race, rr.rule_key AS seed_key, a.id AS ability_id, rr.priority::int AS priority,
           rr.chance_pct::int AS chance_pct, rr.cooldown_s::int AS cooldown_s,
           rr.conditions::jsonb AS conditions, rr.target AS target, rr.min_level::int AS min_level
    FROM race_rule rr
    JOIN "Ability" a ON a.plain_name = rr.ability_name
    JOIN "RaceAbilities" ra ON ra.race = rr.race::"Race" AND ra.ability_id = a.id
), seed AS (
    SELECT raw.*, md5(concat_ws('|', raw.ability_id, raw.priority, raw.chance_pct, raw.cooldown_s, coalesce(raw.conditions::text, ''), raw.target, coalesce(raw.min_level::text, ''))) AS seed_hash FROM raw
)
INSERT INTO "RaceAiRules" (race, ability_id, priority, chance_pct, cooldown_s, conditions,
    target, min_level, enabled, seed_key, seed_hash)
SELECT s.race, s.ability_id, s.priority, s.chance_pct, s.cooldown_s, s.conditions,
       s.target, s.min_level, true, s.seed_key, s.seed_hash
FROM seed s
WHERE NOT EXISTS (SELECT 1 FROM "RaceAiRules" x WHERE x.race = s.race AND x.ability_id = s.ability_id
                  AND x.priority = s.priority AND x.seed_key IS DISTINCT FROM s.seed_key)
ON CONFLICT (seed_key) DO UPDATE SET
    race = EXCLUDED.race, ability_id = EXCLUDED.ability_id, priority = EXCLUDED.priority,
    chance_pct = EXCLUDED.chance_pct, cooldown_s = EXCLUDED.cooldown_s, conditions = EXCLUDED.conditions,
    target = EXCLUDED.target, min_level = EXCLUDED.min_level, seed_hash = EXCLUDED.seed_hash
WHERE "RaceAiRules".seed_hash IS NOT DISTINCT FROM md5(concat_ws('|', "RaceAiRules".ability_id, "RaceAiRules".priority, "RaceAiRules".chance_pct, "RaceAiRules".cooldown_s, coalesce("RaceAiRules".conditions::text, ''), "RaceAiRules".target, coalesce("RaceAiRules".min_level::text, '')))
  AND "RaceAiRules".seed_hash IS DISTINCT FROM EXCLUDED.seed_hash;

WITH race_rule(race, rule_key, ability_name, priority, chance_pct, cooldown_s, conditions, target, min_level) AS (VALUES
    ('DRAGON_FIRE', 'DRAGON_FIRE:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_FIRE', 'DRAGON_FIRE:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_FIRE', 'DRAGON_FIRE:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_FROST', 'DRAGON_FROST:BREATHE_FROST', 'BREATHE_FROST', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_FROST', 'DRAGON_FROST:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_FROST', 'DRAGON_FROST:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_ACID', 'DRAGON_ACID:BREATHE_ACID', 'BREATHE_ACID', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_ACID', 'DRAGON_ACID:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_ACID', 'DRAGON_ACID:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_GAS', 'DRAGON_GAS:BREATHE_GAS', 'BREATHE_GAS', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GAS', 'DRAGON_GAS:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_GAS', 'DRAGON_GAS:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_LIGHTNING', 'DRAGON_LIGHTNING:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_FIRE', 'DRAGONBORN_FIRE:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:BREATHE_FROST', 'BREATHE_FROST', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_FROST', 'DRAGONBORN_FROST:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:BREATHE_ACID', 'BREATHE_ACID', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_ACID', 'DRAGONBORN_ACID:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:BREATHE_GAS', 'BREATHE_GAS', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_GAS', 'DRAGONBORN_GAS:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 10, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGONBORN_LIGHTNING', 'DRAGONBORN_LIGHTNING:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"composition": ["FIRE", "LAVA"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_GAS', 'BREATHE_GAS', 11, 100, 0, '{"composition": ["METAL", "BONE", "PLANT"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FROST', 'BREATHE_FROST', 12, 100, 0, '{"composition": ["WATER", "ICE", "MIST"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_ACID', 'BREATHE_ACID', 13, 100, 0, '{"composition": ["EARTH", "STONE"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 14, 100, 0, '{"composition": ["AIR", "ETHER"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FIRE:other', 'BREATHE_FIRE', 20, 100, 0, '{"in_combat": true, "level_roll": {"max": 1, "min": 0}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_GAS:other', 'BREATHE_GAS', 21, 100, 0, '{"in_combat": true, "level_roll": {"max": 2, "min": 1}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_FROST:other', 'BREATHE_FROST', 22, 100, 0, '{"in_combat": true, "level_roll": {"max": 3, "min": 2}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_ACID:other', 'BREATHE_ACID', 23, 100, 0, '{"in_combat": true, "level_roll": {"max": 4, "min": 3}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:BREATHE_LIGHTNING:other', 'BREATHE_LIGHTNING', 24, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 4}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:SWEEP', 'SWEEP', 40, 100, 0, '{"in_combat": true, "level_roll": {"max": 10, "min": 5}}', 'auto', 20),
    ('DRAGON_GENERAL', 'DRAGON_GENERAL:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25),
    ('DEMON', 'DEMON:BREATHE_FIRE', 'BREATHE_FIRE', 10, 100, 0, '{"composition": ["FIRE", "LAVA"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_GAS', 'BREATHE_GAS', 11, 100, 0, '{"composition": ["METAL", "BONE", "PLANT"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FROST', 'BREATHE_FROST', 12, 100, 0, '{"composition": ["WATER", "ICE", "MIST"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_ACID', 'BREATHE_ACID', 13, 100, 0, '{"composition": ["EARTH", "STONE"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_LIGHTNING', 'BREATHE_LIGHTNING', 14, 100, 0, '{"composition": ["AIR", "ETHER"], "in_combat": true, "level_roll": {"max": 5, "min": 0}}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FIRE:other', 'BREATHE_FIRE', 20, 100, 0, '{"in_combat": true, "level_roll": {"max": 1, "min": 0}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_GAS:other', 'BREATHE_GAS', 21, 100, 0, '{"in_combat": true, "level_roll": {"max": 2, "min": 1}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_FROST:other', 'BREATHE_FROST', 22, 100, 0, '{"in_combat": true, "level_roll": {"max": 3, "min": 2}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_ACID:other', 'BREATHE_ACID', 23, 100, 0, '{"in_combat": true, "level_roll": {"max": 4, "min": 3}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:BREATHE_LIGHTNING:other', 'BREATHE_LIGHTNING', 24, 100, 0, '{"in_combat": true, "level_roll": {"max": 5, "min": 4}, "not_composition": ["AIR", "BONE", "EARTH", "ETHER", "FIRE", "ICE", "LAVA", "METAL", "MIST", "PLANT", "STONE", "WATER"]}', 'auto', 15),
    ('DEMON', 'DEMON:ROAR', 'ROAR', 50, 100, 0, '{"in_combat": true, "level_roll": {"max": 15, "min": 10}}', 'auto', 25)
), raw AS (
    SELECT rr.race::"Race" AS race, rr.rule_key AS seed_key, a.id AS ability_id, rr.priority::int AS priority,
           rr.chance_pct::int AS chance_pct, rr.cooldown_s::int AS cooldown_s,
           rr.conditions::jsonb AS conditions, rr.target AS target, rr.min_level::int AS min_level
    FROM race_rule rr
    JOIN "Ability" a ON a.plain_name = rr.ability_name
    JOIN "RaceAbilities" ra ON ra.race = rr.race::"Race" AND ra.ability_id = a.id
), seed AS (
    SELECT raw.*, md5(concat_ws('|', raw.ability_id, raw.priority, raw.chance_pct, raw.cooldown_s, coalesce(raw.conditions::text, ''), raw.target, coalesce(raw.min_level::text, ''))) AS seed_hash FROM raw
)
UPDATE "RaceAiRules" r SET enabled = false
WHERE r.seed_key IS NOT NULL AND r.enabled AND r.seed_hash IS NOT DISTINCT FROM md5(concat_ws('|', r.ability_id, r.priority, r.chance_pct, r.cooldown_s, coalesce(r.conditions::text, ''), r.target, coalesce(r.min_level::text, '')))
  AND NOT EXISTS (SELECT 1 FROM seed s WHERE s.seed_key = r.seed_key);

COMMIT;
