#!/usr/bin/env python3
"""Generate the backfill for worn flag effects (ObjectEffects `status` rows).

Reads lib/world/obj/*.obj with the same parser + flag mapping the importer uses
(fierylib.converters.flag_normalizer.mob_default_status_flags, i.e. the shared
MOB_EFFECT_FLAG_TO_STATUS_FLAG table) and emits data/sql/2026-10-08-object-flag-effects.sql:
one ObjectEffects row per object (effect = the generic `status` Effect,
modifier_data = {"flags": [...]}). Rows are inserted only for objects that do not
already have a `status` row, so it is idempotent and never clobbers builder edits.

Usage:
    python scripts/gen_object_flag_effects_sql.py [--lib ../lib] [--out PATH]
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from mud.mudfile import MudData  # noqa: E402
from mud.types.object import Object  # noqa: E402

from fierylib.converters import normalize_flags  # noqa: E402
from fierylib.converters.flag_normalizer import mob_default_status_flags  # noqa: E402

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "data" / "sql" / "2026-10-08-object-flag-effects.sql"

HEADER = """-- ObjectEffects backfill: worn status effects from legacy object EFF_* flags.
--
-- The importer (ObjectImporter.add_status_effect) now writes these rows on import;
-- this patch gives existing databases the same data without a reimport. One row per
-- object: effect = the generic `status` Effect, modifier_data = {{"flags": [<status flag>, ...]}}
-- (fierymud-rs installs a marker per flag while the item is worn).
-- Legacy flag -> status flag mapping: MOB_EFFECT_FLAG_TO_STATUS_FLAG in
-- src/fierylib/converters/flag_normalizer.py (DETECT_INVIS -> detect_invisible, ...).
-- Legacy flags with no status mapping are skipped.
--
-- Idempotent and builder-safe: "ObjectEffects" has no unique key, so the insert is
-- guarded with NOT EXISTS on (object, `status` effect); an object that already has a
-- status row (imported or builder-edited) is left untouched, as are its other rows.
-- Objects missing from "Objects" are skipped by the join. Data only, no ownership changes.
-- Generated by scripts/gen_object_flag_effects_sql.py from lib/world/obj/*.obj
-- (id = object vnum - zone*100). {n_rows} rows across {n_zones} zones.
-- Flag usage (objects per flag): {usage}

BEGIN;

INSERT INTO "ObjectEffects" (object_zone_id, object_id, effect_id, strength, modifier_data)
SELECT v.zone_id, v.object_id, e.id, 1, v.flags::jsonb
FROM (VALUES
"""

FOOTER = """) AS v(zone_id, object_id, flags)
JOIN "Effect" e ON e.name = 'status'
JOIN "Objects" o ON o.zone_id = v.zone_id AND o.id = v.object_id
WHERE NOT EXISTS (
    SELECT 1 FROM "ObjectEffects" oe
    WHERE oe.object_zone_id = v.zone_id AND oe.object_id = v.object_id AND oe.effect_id = e.id
);

COMMIT;
"""


def collect(lib: Path):
    rows = []
    usage: Counter = Counter()
    skipped: Counter = Counter()
    failed = []
    for f in sorted((p for p in lib.glob("world/obj/*.obj") if p.stem.isdigit()), key=lambda p: int(p.stem)):
        zone = int(f.stem)
        try:
            objs = Object.parse(MudData(f.read_text().split("\n")))
        except Exception as e:  # unparseable file: the importer skips it too
            failed.append((f.name, str(e)))
            continue
        for obj in objs:
            flags, skip = mob_default_status_flags(normalize_flags(obj.effects or obj.effect_flags or []))
            skipped.update(skip)
            if flags:
                usage.update(flags)
                rows.append((zone, obj.id - zone * 100, flags))
    return rows, usage, skipped, failed


def render(rows, usage) -> str:
    values = ",\n".join(f"    ({z}, {i}, '{json.dumps({'flags': fl})}')" for z, i, fl in rows)
    usage_s = ", ".join(f"{k}={v}" for k, v in sorted(usage.items()))
    return HEADER.format(n_rows=len(rows), n_zones=len({r[0] for r in rows}), usage=usage_s) + values + "\n" + FOOTER


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lib", default=str(Path(__file__).resolve().parent.parent.parent / "lib"))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    rows, usage, skipped, failed = collect(Path(args.lib))
    Path(args.out).write_text(render(rows, usage))
    print(f"wrote {args.out}: {len(rows)} rows")
    print("usage:", dict(sorted(usage.items())))
    print("skipped legacy flags:", dict(skipped))
    for name, err in failed:
        print(f"unparseable {name}: {err}", file=sys.stderr)


if __name__ == "__main__":
    main()
