#!/usr/bin/env python3
"""Generate the RaceEffects fix patch from data/races.json.

The old importer linked every race to the generic `status` Effect with an empty
modifier_data ({}), which the runtime would read as the Effect's default flag
(`bless`). This emits data/sql/2026-10-08-race-effects.sql: one RaceEffects row per
race (effect = `status`, modifier_data = {"flags": [...]}) built from the legacy
PERM_EFF(...) table in races.cpp (via races.json permanentEffects) through the same
legacy EFF_* -> status flag mapping MobDefaultEffects uses.

Usage:
    poetry run python scripts/gen_race_effects_sql.py [--out PATH]
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from fierylib.converters.flag_normalizer import mob_default_status_flags  # noqa: E402
from fierylib.importers.race_importer import RACE_NAME_TO_ENUM  # noqa: E402

DEFAULT_OUT = ROOT / "data" / "sql" / "2026-10-08-race-effects.sql"

HEADER = """-- RaceEffects: innate (permanent) race effects as real status flags.
--
-- The old importer linked each race to the generic `status` Effect with empty
-- modifier_data ({{}}); the runtime would have read that as the Effect default flag
-- (`bless`). Now each race has ONE row (the table is unique on race+effect):
-- effect = `status`, modifier_data = {{"flags": [<status flag>, ...]}}, built from the
-- legacy PERM_EFF(RACE_x, EFF_y) table in fierymud_legacy/src/races.cpp (init_races)
-- via the MobDefaultEffects mapping (EFF_INFRAVISION -> infravision, EFF_SENSE_LIFE ->
-- detect_life, ...). Also adds HALF_ELF, whose row the importer used to drop.
-- Generated by scripts/gen_race_effects_sql.py from data/races.json. {n_rows} races.
--
-- Idempotent and builder-safe: only rows still in the placeholder shape
-- (modifier_data = '{{}}') are rewritten; any row a builder already edited is left
-- alone, and a second run changes nothing. Leftover placeholder rows for races with
-- no innate effects are removed.

BEGIN;

INSERT INTO "RaceEffects" (race, effect_id, strength, modifier_data)
SELECT v.race::"Race", e.id, 1, v.flags::jsonb
FROM (VALUES
"""

FOOTER = """) AS v(race, flags)
JOIN "Effect" e ON e.name = 'status'
ON CONFLICT (race, effect_id) DO UPDATE
    SET modifier_data = EXCLUDED.modifier_data
    WHERE "RaceEffects".modifier_data = '{}'::jsonb;

DELETE FROM "RaceEffects" re
USING "Effect" e
WHERE re.effect_id = e.id AND e.name = 'status' AND re.modifier_data = '{}'::jsonb;

COMMIT;
"""


def collect(races_json: Path):
    rows = []
    for race in json.loads(races_json.read_text())["races"]:
        enum = RACE_NAME_TO_ENUM.get(race["name"].lower().replace(" ", "_").replace("-", "_"))
        flags, _skipped = mob_default_status_flags(race.get("permanentEffects") or [])
        if enum and flags:
            rows.append((enum.value, flags))
    return sorted(rows)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--races", default=str(ROOT / "data" / "races.json"))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()
    rows = collect(Path(args.races))
    values = ",\n".join(f"    ('{r}', '{json.dumps({'flags': fl})}')" for r, fl in rows)
    Path(args.out).write_text(HEADER.format(n_rows=len(rows)) + values + "\n" + FOOTER)
    print(f"wrote {args.out}: {len(rows)} rows")


if __name__ == "__main__":
    main()
