#!/usr/bin/env python3
"""Generate the prod patch moving mob bare-hand damage dice to the legacy 64c30ccb formula.

Reads lib/world/mob/*.mob with the same parser and the same (zone, id) mapping as the
importer (zone = file stem, id = vnum - zone*100), computes

  OLD = pre-change fierylib dice (private copy of the old get_set_dice below) + file modifiers
  NEW = fierylib.combat_formulas.get_set_dice (legacy 64c30ccb) + file modifiers

and emits data/sql/2026-10-08-mob-damage-dice.sql: one UPDATE per mob whose
(damage_dice_num, damage_dice_size) changes, guarded on the OLD values so a mob that was
edited in Muditor since import is skipped. Re-running the patch is a no-op.
damage_dice_bonus is unchanged by this change (get_set_hd is untouched).

Usage:
    poetry run python scripts/gen_mob_dice_sql.py [--lib ../lib] [--out PATH]
"""

import argparse
import sys
from collections import Counter
from pathlib import Path
from typing import Tuple

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from mud.mudfile import MudData  # noqa: E402
from mud.types.mob import Mob  # noqa: E402

from fierylib.combat_formulas import get_class_dice_factor, get_race_dice_factor  # noqa: E402
from fierylib.importers.mob_importer import apply_damage_dice_modifiers  # noqa: E402

DEFAULT_OUT = ROOT / "data" / "sql" / "2026-10-08-mob-damage-dice.sql"
BANDS = ["<22", "22-39", "40-59", "60+"]


def old_get_set_dice(level: int, race_factor: int, class_factor: int) -> Tuple[int, int]:
    """Private copy of fierylib's get_set_dice BEFORE the 64c30ccb port (what prod was imported with)."""
    if level < 10:
        dice = max(1, int((level / 3.0) + 0.5))
    elif level < 30:
        dice = int((level / 3.0) + 0.5)
    elif level <= 50:
        dice = int((level / 3.0) + 0.5)
    else:
        dice = int((level / 2.5) + 0.5)
    sfactor = (race_factor + class_factor) / 2.0
    dice = int((sfactor * dice) / 100.0)
    dice = max(1, dice)
    if level < 10:
        face = 3
    elif level < 26:
        face = 4
    elif level < 36:
        face = 4
    elif level <= 50:
        face = 5
    elif level <= 60:
        face = 8
    else:
        face = 10
    return (dice, face)


def band(level: int) -> str:
    return BANDS[0] if level < 22 else BANDS[1] if level < 40 else BANDS[2] if level < 60 else BANDS[3]


def collect(lib: Path):
    changes, failed, total = [], [], 0
    for f in sorted((p for p in lib.glob("world/mob/*.mob") if p.stem.isdigit()), key=lambda p: int(p.stem)):
        zone = int(f.stem)
        try:
            mobs = Mob.parse(MudData(f.read_text().split("\n")))
        except Exception as e:  # unparseable file: the importer skips it too
            failed.append((f.name, str(e)))
            continue
        for mob in mobs:
            total += 1
            race = mob.race.name if hasattr(mob.race, "name") else str(mob.race).upper()
            cls = mob.mob_class.name if hasattr(mob.mob_class, "name") else str(mob.mob_class).upper()
            rf, cf = get_race_dice_factor(race), get_class_dice_factor(cls)
            mn, ms = mob.damage_dice.num, mob.damage_dice.size
            old_base = old_get_set_dice(mob.level, rf, cf)
            old = (max(0, old_base[0] + mn), max(1, old_base[1] + ms))
            new = apply_damage_dice_modifiers(mob.level, rf, cf, mn, ms)
            if old != new:
                changes.append((zone, mob.id - zone * 100, mob.level, old, new))
    return changes, failed, total


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lib", default=str(ROOT.parent / "lib"))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    changes, failed, total = collect(Path(args.lib))
    dist = Counter(band(lvl) for _, _, lvl, _, _ in changes)

    lines = [
        "-- Mob bare-hand damage dice: switch to the legacy 64c30ccb get_set_dice formula.",
        "--",
        "-- dice count = level/3 (floor, all levels); face = 3 (<22), 4 (22-39), level/10+1 (40+),",
        "-- plus the .mob file's ex_damnodice/ex_damsizedice modifiers (unchanged). Bonus is untouched.",
        f"-- {len(changes)} of {total} legacy mobs change; by level band: "
        + ", ".join(f"{b}={dist.get(b, 0)}" for b in BANDS),
        "--",
        "-- Each UPDATE is guarded on the OLD (num, size) values, so mobs edited in Muditor since the",
        "-- import are skipped, and re-running is a no-op (guard no longer matches).",
        "-- Generated by scripts/gen_mob_dice_sql.py (zone = file stem, id = vnum - zone*100).",
        "",
        "BEGIN;",
        "",
    ]
    for zone, mid, _lvl, (on, os_), (nn, ns) in changes:
        lines.append(
            f'UPDATE "Mobs" SET damage_dice_num = {nn}, damage_dice_size = {ns} '
            f"WHERE zone_id = {zone} AND id = {mid} AND damage_dice_num = {on} AND damage_dice_size = {os_};"
        )
    lines += ["", "COMMIT;", ""]
    Path(args.out).write_text("\n".join(lines))
    print(f"wrote {args.out}: {len(changes)} of {total} mobs change; " + ", ".join(f"{b}={dist.get(b, 0)}" for b in BANDS))
    for name, err in failed:
        print(f"unparseable {name}: {err}", file=sys.stderr)


if __name__ == "__main__":
    main()
