#!/usr/bin/env python3
"""Generate the follow-up object flag backfill (data/sql/2026-10-08-object-flag-effects-2.sql).

Gap left by gen_object_flag_effects_sql.py / 2026-10-08-object-flag-effects.sql:

* legacy object EFF_* bits that the shared mob table does not map but fierymud-rs
  has a counterpart for (OBJECT_EFFECT_FLAG_TO_STATUS_FLAG: PROTECT_EVIL, PROTECT_GOOD,
  TONGUES, FAMILIARITY) are merged into the object's `status` ObjectEffects row;
* MINOR_GLOBE / MAJOR_GLOBE become a `globe` ObjectEffects row (strength = max circle);
* ObjectResistance rows from the protection bits (importer EFFECT_TO_RESISTANCE:
  PROTECT_*, FIRESHIELD/COLDSHIELD, NEGATE_*, STONE_SKIN) that prod/dev never got.

Reads lib/world/obj/*.obj with the importer's parser and mappings.

Usage:
    python scripts/gen_object_flag_effects2_sql.py --lib /path/to/lib [--out PATH]
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from mud.mudfile import MudData  # noqa: E402
from mud.types.object import Object  # noqa: E402

from fierylib.converters import normalize_flags  # noqa: E402
from fierylib.converters.flag_normalizer import (  # noqa: E402
    EFFECT_FLAG_TO_EFFECT_NAME,
    OBJECT_EFFECT_FLAG_TO_STATUS_FLAG,
    mob_default_status_flags,
    object_globe_circle,
)
from fierylib.importers.object_importer import EFFECT_TO_RESISTANCE  # noqa: E402

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "data" / "sql" / "2026-10-08-object-flag-effects-2.sql"

HEADER = """-- Object flag effects, part 2: bits left unmapped by 2026-10-08-object-flag-effects.sql,
-- plus the ObjectResistance backfill dev/prod never got.
--
-- 1. status flags: legacy PROTECT_EVIL -> protect_evil, PROTECT_GOOD -> protect_good,
--    TONGUES -> language_fluency, FAMILIARITY -> familiarity (OBJECT_EFFECT_FLAG_TO_STATUS_FLAG in
--    src/fierylib/converters/flag_normalizer.py). Objects with a `status` ObjectEffects row get the
--    missing flags appended to modifier_data.flags (existing flags, order and other keys are kept);
--    objects without one get a new row. Re-running adds nothing.
-- 2. worn globe: MINOR_GLOBE / MAJOR_GLOBE -> one `globe` Effect row, strength = max absorbed
--    circle (3 / 6), inserted only if the object has no `globe` row (fierymud-rs MaxAbsorbCircle).
-- 3. ObjectResistance: PROTECT_FIRE/COLD/AIR(shock)/EARTH(acid), FIRESHIELD, COLDSHIELD, NEGATE_*,
--    STONE_SKIN (physical 25) via the importer's EFFECT_TO_RESISTANCE; inserted only where the
--    (object, element) pair has no row (unique key), so existing/builder values are untouched.
-- Not mapped on worn gear: CHARM, TAMED, ON_FIRE, HURT_THROAT (nonsensical state on equipment),
-- VITALITY, GLORY, NO_TRACK (no runtime marker or flag).
-- Objects missing from "Objects" are skipped by the join. Data only, no DDL.
-- Generated by scripts/gen_object_flag_effects2_sql.py from lib/world/obj/*.obj
-- (id = object vnum - zone*100). {n_status} status, {n_globe} globe, {n_res} resistance rows.
-- Flag usage (objects): {usage}

BEGIN;
"""

STATUS_SQL = """
-- 1a. New `status` rows for objects that have none.
INSERT INTO "ObjectEffects" (object_zone_id, object_id, effect_id, strength, modifier_data)
SELECT v.zone_id, v.object_id, e.id, 1, v.flags::jsonb
FROM (VALUES
{rows}
) AS v(zone_id, object_id, flags)
JOIN "Effect" e ON e.name = 'status'
JOIN "Objects" o ON o.zone_id = v.zone_id AND o.id = v.object_id
WHERE NOT EXISTS (
    SELECT 1 FROM "ObjectEffects" oe
    WHERE oe.object_zone_id = v.zone_id AND oe.object_id = v.object_id AND oe.effect_id = e.id
);

-- 1b. Append the missing flags to an existing `status` row (the lowest id when there are several).
WITH v(zone_id, object_id, flags) AS (VALUES
{rows}
), todo AS (
    SELECT oe.id,
           oe.modifier_data,
           COALESCE(oe.modifier_data -> 'flags', '[]'::jsonb) AS old_flags,
           (SELECT COALESCE(jsonb_agg(f ORDER BY f), '[]'::jsonb)
              FROM jsonb_array_elements_text(v.flags::jsonb -> 'flags') f
             WHERE NOT (COALESCE(oe.modifier_data -> 'flags', '[]'::jsonb) @> to_jsonb(f))) AS add_flags
    FROM v
    JOIN "Effect" e ON e.name = 'status'
    JOIN "ObjectEffects" oe ON oe.object_zone_id = v.zone_id AND oe.object_id = v.object_id AND oe.effect_id = e.id
    WHERE oe.id = (SELECT MIN(x.id) FROM "ObjectEffects" x
                   WHERE x.object_zone_id = v.zone_id AND x.object_id = v.object_id AND x.effect_id = e.id)
      AND jsonb_typeof(COALESCE(oe.modifier_data -> 'flags', '[]'::jsonb)) = 'array'
)
UPDATE "ObjectEffects" oe
SET modifier_data = jsonb_set(todo.modifier_data, '{{flags}}', todo.old_flags || todo.add_flags)
FROM todo
WHERE oe.id = todo.id AND todo.add_flags <> '[]'::jsonb;
"""

GLOBE_SQL = """
-- 2. Worn globe (strength = max absorbed circle), only where the object has no `globe` row.
INSERT INTO "ObjectEffects" (object_zone_id, object_id, effect_id, strength, modifier_data)
SELECT v.zone_id, v.object_id, e.id, v.circle, '{{}}'::jsonb
FROM (VALUES
{rows}
) AS v(zone_id, object_id, circle)
JOIN "Effect" e ON e.name = 'globe'
JOIN "Objects" o ON o.zone_id = v.zone_id AND o.id = v.object_id
WHERE NOT EXISTS (
    SELECT 1 FROM "ObjectEffects" oe
    WHERE oe.object_zone_id = v.zone_id AND oe.object_id = v.object_id AND oe.effect_id = e.id
);
"""

RESISTANCE_SQL = """
-- 3. ObjectResistance backfill (importer EFFECT_TO_RESISTANCE; strongest value per element).
INSERT INTO "ObjectResistance" (object_zone_id, object_id, element, value, allow_absorption)
SELECT v.zone_id, v.object_id, v.element::"ElementType", v.value, false
FROM (VALUES
{rows}
) AS v(zone_id, object_id, element, value)
JOIN "Objects" o ON o.zone_id = v.zone_id AND o.id = v.object_id
WHERE NOT EXISTS (
    SELECT 1 FROM "ObjectResistance" r
    WHERE r.object_zone_id = v.zone_id AND r.object_id = v.object_id AND r.element = v.element::"ElementType"
);
"""

FOOTER = "\nCOMMIT;\n"


def collect(lib: Path):
    """Return (status_rows, globe_rows, resistance_rows, usage, failed)."""
    status_rows, globe_rows, res_rows = [], [], []
    usage: Counter = Counter()
    failed = []
    for f in sorted((p for p in lib.glob("world/obj/*.obj") if p.stem.isdigit()), key=lambda p: int(p.stem)):
        zone = int(f.stem)
        try:
            objs = Object.parse(MudData(f.read_text().split("\n")))
        except Exception as e:  # unparseable file: the importer skips it too
            failed.append((f.name, str(e)))
            continue
        for obj in objs:
            oid = obj.id - zone * 100
            effects = normalize_flags(obj.effects or obj.effect_flags or [])
            flags, _ = mob_default_status_flags(effects, OBJECT_EFFECT_FLAG_TO_STATUS_FLAG)
            if flags:
                usage.update(flags)
                status_rows.append((zone, oid, flags))
            circle = object_globe_circle(effects)
            if circle:
                usage.update(["globe_minor" if circle == 3 else "globe_major"])
                globe_rows.append((zone, oid, circle))
            best: dict[str, int] = {}
            for name in dict.fromkeys(EFFECT_FLAG_TO_EFFECT_NAME[e] for e in effects if e in EFFECT_FLAG_TO_EFFECT_NAME):
                mapping = EFFECT_TO_RESISTANCE.get(name)
                if mapping and mapping[1] > best.get(mapping[0], 0):
                    best[mapping[0]] = mapping[1]
            for element, value in sorted(best.items()):
                usage.update([f"resist_{element}"])
                res_rows.append((zone, oid, element, value))
    return status_rows, globe_rows, res_rows, usage, failed


def render(status_rows, globe_rows, res_rows, usage) -> str:
    out = HEADER.format(
        n_status=len(status_rows),
        n_globe=len(globe_rows),
        n_res=len(res_rows),
        usage=", ".join(f"{k}={v}" for k, v in sorted(usage.items())),
    )
    if status_rows:
        rows = ",\n".join(f"    ({z}, {i}, '{json.dumps({'flags': fl})}')" for z, i, fl in status_rows)
        out += STATUS_SQL.format(rows=rows)
    if globe_rows:
        out += GLOBE_SQL.format(rows=",\n".join(f"    ({z}, {i}, {c})" for z, i, c in globe_rows))
    if res_rows:
        out += RESISTANCE_SQL.format(rows=",\n".join(f"    ({z}, {i}, '{el}', {v})" for z, i, el, v in res_rows))
    return out + FOOTER


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lib", default=str(Path(__file__).resolve().parent.parent.parent / "lib"))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    status_rows, globe_rows, res_rows, usage, failed = collect(Path(args.lib))
    Path(args.out).write_text(render(status_rows, globe_rows, res_rows, usage))
    print(f"wrote {args.out}: {len(status_rows)} status, {len(globe_rows)} globe, {len(res_rows)} resistance rows")
    print("usage:", dict(sorted(usage.items())))
    for name, err in failed:
        print(f"unparseable {name}: {err}", file=sys.stderr)


if __name__ == "__main__":
    main()
