#!/usr/bin/env python3
"""Generate the prod patch for creature composition (what a mob/race is made of).

Reads lib/world/mob/*.mob with the same parser the importer uses (`Composition:` key)
and data/races.json (race defaults, ported from races.cpp `def_composition`) and
emits data/sql/2026-10-07-composition.sql:

  * CREATE TYPE "Composition" (guarded), ADD COLUMN IF NOT EXISTS on "Mobs" and "Races"
    (exactly what `prisma db push` would do),
  * UPDATE only non-FLESH rows, and only where the column is still the FLESH default,
    so re-running is a no-op and never clobbers a builder's edit.

Usage:
    poetry run python scripts/gen_composition_sql.py [--lib ../lib] [--out PATH]
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from mud.mudfile import MudData  # noqa: E402
from mud.types.mob import Mob  # noqa: E402

DEFAULT_OUT = ROOT / "data" / "sql" / "2026-10-07-composition.sql"
RACES_JSON = ROOT / "data" / "races.json"

# Order mirrors muditor schema.prisma `enum Composition` / legacy COMP_* constants.
COMPOSITIONS = ["FLESH", "EARTH", "AIR", "FIRE", "WATER", "ICE", "MIST", "ETHER", "METAL", "STONE", "BONE", "LAVA", "PLANT"]

HEADER = """-- Composition: what a creature is physically made of (flesh, stone, plant, ...).
--
-- Mirrors `prisma db push` for the new enum + columns, then backfills non-FLESH
-- values from the legacy data so prod does not need a reimport:
--   * "Mobs".composition          <- `Composition:` in lib/world/mob/*.mob ({n_mobs} mobs, {mob_usage})
--   * "Races".default_composition <- races.cpp def_composition ({n_races} races: {race_list})
-- FLESH is the column default, so only non-FLESH rows are listed.
--
-- Idempotent: type creation is guarded, columns use IF NOT EXISTS, and the UPDATEs only
-- touch rows still at FLESH (never overwrite a builder's edit; re-run is a no-op).
-- Mobs missing from "Mobs" are skipped by the join.
-- Generated by scripts/gen_composition_sql.py (id = mob vnum - zone*100).

BEGIN;

DO $$ BEGIN
    CREATE TYPE "Composition" AS ENUM ({enum_values});
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Mobs" ADD COLUMN IF NOT EXISTS "composition" "Composition" NOT NULL DEFAULT 'FLESH';
ALTER TABLE "Races" ADD COLUMN IF NOT EXISTS "default_composition" "Composition" NOT NULL DEFAULT 'FLESH';

"""

RACES_SQL = """UPDATE "Races" SET "default_composition" = v.comp::"Composition"
FROM (VALUES
{values}
) AS v(race, comp)
WHERE "Races"."race" = v.race::"Race" AND "Races"."default_composition" = 'FLESH';

"""

MOBS_SQL = """UPDATE "Mobs" m SET "composition" = v.comp::"Composition"
FROM (VALUES
{values}
) AS v(zone_id, mob_id, comp)
WHERE m.zone_id = v.zone_id AND m.id = v.mob_id AND m."composition" = 'FLESH';

COMMIT;
"""


def collect_mobs(lib: Path):
    rows = []
    failed = []
    for f in sorted((p for p in lib.glob("world/mob/*.mob") if p.stem.isdigit()), key=lambda p: int(p.stem)):
        zone = int(f.stem)
        try:
            mobs = Mob.parse(MudData(f.read_text().split("\n")))
        except Exception as e:  # unparseable file: the importer skips it too
            failed.append((f.name, str(e)))
            continue
        for mob in mobs:
            comp = mob.composition.name
            if comp != "FLESH":
                rows.append((zone, mob.id - zone * 100, comp))
    return rows, failed


def collect_races():
    from fierylib.importers.race_importer import RACE_NAME_TO_ENUM

    rows = []
    for r in json.loads(RACES_JSON.read_text())["races"]:
        if r["defaultComposition"] != "FLESH":
            rows.append((RACE_NAME_TO_ENUM[r["name"].lower().replace(" ", "_").replace("-", "_")].name, r["defaultComposition"]))
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lib", default=str(ROOT.parent / "lib"))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    mob_rows, failed = collect_mobs(Path(args.lib))
    race_rows = collect_races()
    usage = Counter(c for _, _, c in mob_rows)

    text = HEADER.format(
        n_mobs=len(mob_rows),
        mob_usage=", ".join(f"{k}={v}" for k, v in sorted(usage.items())),
        n_races=len(race_rows),
        race_list=", ".join(f"{r}={c}" for r, c in race_rows),
        enum_values=", ".join(f"'{c}'" for c in COMPOSITIONS),
    )
    text += RACES_SQL.format(values=",\n".join(f"    ('{r}', '{c}')" for r, c in race_rows))
    text += MOBS_SQL.format(values=",\n".join(f"    ({z}, {i}, '{c}')" for z, i, c in mob_rows))
    Path(args.out).write_text(text)
    print(f"wrote {args.out}: {len(mob_rows)} mob rows, {len(race_rows)} race rows")
    for name, err in failed:
        print(f"unparseable {name}: {err}", file=sys.stderr)


if __name__ == "__main__":
    main()
