#!/usr/bin/env python3
"""Generate the prod backfill for MobDefaultEffects from the legacy mob files.

Reads lib/world/mob/*.mob with the same parser + flag mapping the importer uses
(fierylib.converters.flag_normalizer.mob_default_status_flags) and emits
data/sql/2026-10-07-mob-default-effects.sql: one MobDefaultEffects row per mob
(effect = the generic `status` Effect, modifier_data = {"flags": [...]}), inserted
with ON CONFLICT DO NOTHING so it is idempotent and never clobbers builder edits.

Usage:
    poetry run python scripts/gen_mob_default_effects_sql.py [--lib ../lib] [--out PATH]
"""

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from mud.bitflags import BitFlags  # noqa: E402
from mud.mudfile import MudData  # noqa: E402
from mud.types.mob import Mob  # noqa: E402

from fierylib.converters.flag_normalizer import mob_default_status_flags  # noqa: E402

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "data" / "sql" / "2026-10-07-mob-default-effects.sql"

HEADER = """-- MobDefaultEffects backfill: innate status effects from legacy mob EFF_* flags.
--
-- The importer (MobImporter.sync_default_effects) now writes these rows on import;
-- this patch gives prod the same data without a reimport. One row per mob:
-- effect = the generic `status` Effect, modifier_data = {{"flags": [<status flag>, ...]}}
-- (the table is unique on (mob, effect), so a mob's status flags share the row).
-- Legacy flag -> status flag mapping: MOB_EFFECT_FLAG_TO_STATUS_FLAG in
-- src/fierylib/converters/flag_normalizer.py (DETECT_INVIS -> detect_invisible, ...).
-- Legacy flags with no status mapping are skipped.
--
-- Idempotent: ON CONFLICT DO NOTHING (re-running is a no-op and never overwrites a
-- builder's edit); mobs missing from "Mobs" are skipped by the join.
-- Generated by scripts/gen_mob_default_effects_sql.py from lib/world/mob/*.mob
-- (id = mob vnum - zone*100). {n_rows} rows across {n_zones} zones.
-- Flag usage: {usage}

BEGIN;

INSERT INTO "MobDefaultEffects" (mob_zone_id, mob_id, effect_id, strength, modifier_data)
SELECT v.zone_id, v.mob_id, e.id, 1, v.flags::jsonb
FROM (VALUES
"""

FOOTER = """) AS v(zone_id, mob_id, flags)
JOIN "Effect" e ON e.name = 'status'
JOIN "Mobs" m ON m.zone_id = v.zone_id AND m.id = v.mob_id
ON CONFLICT (mob_zone_id, mob_id, effect_id) DO NOTHING;

COMMIT;
"""


def collect(lib: Path):
    rows = []
    usage: Counter = Counter()
    skipped: Counter = Counter()
    failed = []
    for f in sorted((p for p in lib.glob("world/mob/*.mob") if p.stem.isdigit()), key=lambda p: int(p.stem)):
        zone = int(f.stem)
        try:
            mobs = Mob.parse(MudData(f.read_text().split("\n")))
        except Exception as e:  # unparseable file: the importer skips it too
            failed.append((f.name, str(e)))
            continue
        for mob in mobs:
            raw = mob.effect_flags.json_repr() if isinstance(mob.effect_flags, BitFlags) else (mob.effect_flags or [])
            flags, skip = mob_default_status_flags(raw)
            skipped.update(skip)
            if flags:
                usage.update(flags)
                rows.append((zone, mob.id - zone * 100, flags))
    return rows, usage, skipped, failed


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lib", default=str(Path(__file__).resolve().parent.parent.parent / "lib"))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    rows, usage, skipped, failed = collect(Path(args.lib))
    values = ",\n".join(
        f"    ({z}, {i}, '{json.dumps({'flags': fl})}')" for z, i, fl in rows
    )
    usage_s = ", ".join(f"{k}={v}" for k, v in sorted(usage.items()))
    text = HEADER.format(n_rows=len(rows), n_zones=len({r[0] for r in rows}), usage=usage_s) + values + "\n" + FOOTER
    Path(args.out).write_text(text)
    print(f"wrote {args.out}: {len(rows)} rows")
    print("skipped legacy flags:", dict(skipped))
    for name, err in failed:
        print(f"unparseable {name}: {err}", file=sys.stderr)


if __name__ == "__main__":
    main()
