#!/usr/bin/env python3
"""
Generate Prisma schema enum definitions from Python source of truth.

This script reads enum definitions from mud/types/ modules and flag lists
from mud/flags.py, converts them to Prisma SCREAMING_SNAKE_CASE format,
and writes them to prisma/enums.prisma.

Usage:
    poetry run python scripts/generate_prisma_enums.py
"""

import re
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from mud.types import (
    Race, Gender, Position, Stance, LifeForce, Composition,
    Class, Direction, WearFlags, ScriptType, Size, DamageType
)
from mud.flags import (
    MOB_FLAGS, EFFECTS, ROOM_FLAGS, OBJECT_FLAGS,
    TRIGGER_TYPES, SHOP_FLAGS, SHOP_TRADES_WITH,
    RESET_MODES, HEMISPHERES, CLIMATES, SECTORS, OBJECT_TYPES,
)


def pascal_to_screaming_snake(name: str) -> str:
    """Convert PascalCase to SCREAMING_SNAKE_CASE"""
    # Insert underscore before uppercase letters (except at start)
    snake = re.sub(r'(?<=[a-z])(?=[A-Z])', '_', name)
    return snake.upper()


def normalize_flag(flag: str) -> str:
    """Normalize flag names to SCREAMING_SNAKE_CASE"""
    # Flags are already in correct format in source, just uppercase and strip
    return flag.upper().strip()


def generate_enum_from_python_enum(enum_class, enum_name: str) -> str:
    """Generate Prisma enum from Python Enum class"""
    lines = [f"enum {enum_name} {{"]
    
    for member in enum_class:
        prisma_name = pascal_to_screaming_snake(member.name)
        lines.append(f"  {prisma_name}")
    
    lines.append("}")
    return "\n".join(lines)


def generate_enum_from_flag_list(flag_list: list, enum_name: str) -> str:
    """Generate Prisma enum from flag list"""
    lines = [f"enum {enum_name} {{"]
    
    seen = set()
    for flag in flag_list:
        if not flag:
            continue
        # Keep UNUSED for database compatibility
        normalized = normalize_flag(flag)
        if normalized not in seen:
            lines.append(f"  {normalized}")
            seen.add(normalized)
    
    lines.append("}")
    return "\n".join(lines)


def main():
    # Get output file path
    output_path = Path(__file__).parent.parent / "prisma" / "enums.prisma"
    
    lines = []
    lines.append("// ============================================================================")
    lines.append("// AUTO-GENERATED ENUMS FROM PYTHON SOURCE")
    lines.append("// Generated by: poetry run python scripts/generate_prisma_enums.py")
    lines.append("// Source of truth: src/mud/types/ and src/mud/flags.py")
    lines.append("// DO NOT EDIT MANUALLY - Run the script to regenerate")
    lines.append("// ============================================================================")
    lines.append("")
    
    # Character/Mob/Object enums from types/__init__.py
    lines.append(generate_enum_from_python_enum(Gender, "Gender"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(Race, "Race"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(Position, "Position"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(LifeForce, "LifeForce"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(Composition, "Composition"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(Stance, "Stance"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(Direction, "Direction"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(Size, "Size"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(DamageType, "DamageType"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(ScriptType, "ScriptType"))
    lines.append("")
    
    # World/Zone enums from flags
    lines.append(generate_enum_from_flag_list(RESET_MODES, "ResetMode"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(HEMISPHERES, "Hemisphere"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(CLIMATES, "Climate"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(SECTORS, "Sector"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(OBJECT_TYPES, "ObjectType"))
    lines.append("")
    
    # Flag list enums
    lines.append(generate_enum_from_flag_list(MOB_FLAGS, "MobFlag"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(EFFECTS, "EffectFlag"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(ROOM_FLAGS, "RoomFlag"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(OBJECT_FLAGS, "ObjectFlag"))
    lines.append("")
    lines.append(generate_enum_from_python_enum(WearFlags, "WearFlag"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(TRIGGER_TYPES, "TriggerFlag"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(SHOP_FLAGS, "ShopFlag"))
    lines.append("")
    lines.append(generate_enum_from_flag_list(SHOP_TRADES_WITH, "ShopTradesWith"))
    lines.append("")
    
    # Write to file
    output_path.write_text("\n".join(lines))
    print(f"✅ Generated Prisma enums at: {output_path}")
    print(f"📊 Total lines: {len(lines)}")


if __name__ == "__main__":
    main()
